import React from "react"
import { Link } from "gatsby"
import Hyperlink from "../components/Hyperlink"
import Section from "../components/Section"
import Note from "../components/Note"

import Layout from "../components/layout"
import SEO from "../components/seo"

var notes = 0;
var sections = 0;
const ConLeibniz = () => (
  <Layout>
    <SEO title="Gottfried Leibniz's Contingency Argument" />
    <script>
        {notes = 0}
        {sections = 0}
    </script>    
    <p>Gottfried Leibniz's <Hyperlink to="https://rationalchristian.wordpress.com/2018/05/20/if-anything-exists-god-exists/">contingency argument is based on his so-called</Hyperlink> "<Hyperlink to="https://en.wikipedia.org/wiki/Principle_of_sufficient_reason">principle of sufficient reason</Hyperlink>" (PSR), which states that everything must have an explanation of its existence. According to the PSR, a thing's existence can be explained either by itself or by another thing. If it exists because of another thing, then its existence is <em>contingent</em> on that other thing, so it is said to <em>exist contingently</em>. Conversely, if its existence is self-explanatory, then it is said to <em>exist necessarily</em>. If it has no explanation at all — a possibility that the PSR denies — then its existence is a <em>brute fact.</em>
    <br /><br />
    Given the PSR, every contingent thing is explained by an ontologically prior thing. That prior thing exists either contingently, necessarily, or as a brute fact. This chain of things contingent on prior things is said to leave three respective possibilities. First, the chain extends backwards infinitely, so everything is contingent on a prior thing but there is no first thing. Second, something exists necessarily, so everything is indirectly contingent on it and it therefore explains everything. Finally, something exists as a brute fact. The last case is only a sufficient explanation if all contingent things are indirectly contingent on the brute fact(s). Anyone using the contingency argument rejects the first and third of those possibilities outright, concluding that the second must be correct.
    <br /><br />
    But Leibniz's contingency argument based on the principle of sufficient reason (PSR) is insufficient to show that God exists. Even ignoring the issue of whether reality <em>could</em> merely be a chain of things contingent on prior things extending backwards to infinity, three objections to the PSR will be described here. Each suffices on its own to refute the PSR. </p>
    <Section num={++sections} summary="The PSR is supposedly a metaphysical first principle with no reason or explanation for its existence, and therefore it is self-defeating.">
        Starting with the easiest objection to state and to notice, the PSR, like Hume's fork, is self-refuting. Those who invoke the PSR call it a metaphysical first principle. As a first principle, it has no reason or explanation for its existence, so its unexplained existence refutes itself.
        <br /><br />
        To avoid this, Dr. Craig tried to weaken the PSR such that there can exist brute facts about the world, but every existing thing requires an explanation. In other words, he tried to save the PSR by drawing a distinction between explaining <em>things</em> and explaining <em>facts.</em> Craig defined facts as "true propositions" which, since they are "abstract objects independent of sentences … exist necessarily, if they exist at all" even though their truth values are contingent.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 107.</Note>
        <br /><br />
        Craig's distinction must be understood either through semantic externalism, which <Hyperlink to="https://en.wikipedia.org/wiki/Semantic_externalism">claims that meanings are at least partly determined by factors external to one's perspective</Hyperlink>; or internalism, which disagrees. Consider externalism first. Craig's "if they exist at all" qualifier alludes to the debate between platonism, which would say that abstract objects exist outside the mind, and nominalism, which disagrees. Given nominalism, propositions and their truth values exist in minds, so both exist contingently. But given platonism, the truth value of a proposition is another abstract object, and therefore metaphysically necessary. Under neither can Craig call one necessary and the other contingent.
        <br /><br />
        Even if facts are understood differently under externalism, Craig has drawn a distinction without a difference. Whether a thing exists or not <em>is</em> a fact. Externalists often define "facts" as "<Hyperlink to="https://plato.stanford.edu/entries/truth-correspondence/#3">portions of reality … that are typically denoted by that-clauses or by sentential gerundives, viz. the fact/state of affairs <em>that snow is white</em>."</Hyperlink> So the fact that a thing exists is the portion of reality including only the thing's existence, which is to say, the fact that it exists <em>is</em> its existence. <em>A thing's existence</em> and <em>the fact that a thing exists</em> are different phrases with one meaning. Since there is no difference between a thing's existence and the fact that a thing exists, there is no difference between explaining one and explaining the other.
        <br /><br />
        Given internalism, which coheres well with the definition of "facts" as true propositions, Craig's distinction falls apart for an entirely different reason: if explaining a thing's existence is distinct from explaining the fact that a thing exists, then it is impossible to explain a thing's existence. If <em>x</em> is the explanation of <em>y</em>, then there is an explanatory relation between <em>x</em> and <em>y</em> — which only means, given internalism, that the mind relates <em>x</em> to <em>y</em>. An explanation is an idea, a conceptual description of how other ideas relate to each other. Consequently, explanations exist only in minds. So there cannot exist an explanation of a thing-itself. If there could, then an explanatory relation must exist between an idea and a thing. But the thing-itself exists outside of the mind, and explanations only exist within the mind.
        <br /><br />
        One may wonder, then, how to explain a thing's existence given internalism. Dr. Craig gave the answer himself: explaining facts, not things. Since facts are ideas under Craig's definition, internalism allows that explanatory relations can exist between them — but not between things themselves. It is possible to explain the fact that a thing exists, but not a thing's existence. Craig's weakened form of the PSR is then <em>completely</em> false: <em>nothing</em> has an explanation of its existence.
        <br /><br />
        In any case, the PSR can only claim at most that a certain subset of facts need an expanation but others do not. Yet it offers no reason or explanation why only facts about a thing's (non)existence need a reason. Any purported reason/explanation for saying that the universe's existence needs a reason/explanation will be arbitrary. Arbitrarily carving out exceptions from this so-called metaphysical first principle may rescue it from self-contradiction, but exposes its absurdity.
        <br /><br />
        A theist may object that any alternative to the PSR will be equally arbitrary, if not more so. Yet consider physical explanations as an alternative. In physics, a thing's existence and behavior are explained in terms of the initial conditions of the universe and the laws of nature: given the initial conditions of a system and laws of nature, one should be able to predict any past or future state of the system. Since explanations themselves assume the laws of nature, the laws of nature themselves cannot be explained. They are therefore a brute fact. The inexplicability of the laws of nature is not arbitrary, though, because it follows from how explanations are defined. Similarly, since some initial conditions of the universe must be given to form an explanation, the initial conditions of the universe themselves are inexplicable. This explanatory system admits brute facts while still affirming that most things need to be explained.
    </Section>
    <Section num={++sections} summary="The PSR conflates the location of a thing's explanation with that thing's necessity, making it ignore the possibility of self-explanatory contingent things and non-self-explanatory necessary things. According to any Christian apologist who endorses the 'transcendental argument for God' (TAG), the laws of logic fall into the latter category, so if the PSR is correct then the TAG must fail.">
        Even ignoring that it is either self-defeating or baselessly arbitrary, the PSR conflates the location of a thing's explanation with the necessity of that thing. It ignores at least three possibilities: a thing without an explanation, a self-explanatory contingent thing, and a necessary thing which is explained by something else. As an example of the latter, some Christian apologists who believe in platonism about abstract objects say that numbers exist necessarily but are only explained by God's existence.<Note num={++notes}>See for example, C. Stephen Layman, <Hyperlink to="https://books.google.hu/books?id=DiuiCE-WmgEC&pg=PA91&lpg=PA91&dq=numbers+exist+because+of+god&source=bl&ots=19b2FXkNFP&sig=aeg3tuRvA34zytyyX-_at6oaMeU&hl=en&sa=X&redir_esc=y#v=onepage&q=maybe numbers do exist of necessity&f=false"><em>Letters to Doubting Thomas: A Case for the Existence of God</em> p. 90</Hyperlink>, <Hyperlink to="https://archive.is/OXTMa">archive.is</Hyperlink>.</Note> If the PSR was true, metaphysically necessary numbers would be self-explanatory instead.
        <br /><br />
        As another example, <Hyperlink to="https://answersingenesis.org/world-religions/atheism/atheism-an-irrational-worldview/">Jason Lisle</Hyperlink>'s and <Hyperlink to="https://carm.org/transcendental-argument">Matt Slick</Hyperlink>'s "transcendental argument for God" (TAG) claims that only God's existence can explain the metaphysically necessary laws of logic. If the PSR is correct, and the "laws of logic" really exist outside of minds (as both apologists assume), then the laws of logic are self-explanatory. But Slick claimed that calling the metaphysically necessary laws of logic self-explanatory "does not provide an explanation for their existence." So the PSR contradicts these apologists' so-called "transcendental argument for God" (TAG). So a Christian apologist must choose between the TAG on the one hand and the PSR on the other. Both of these examples show possibilities that the PSR categorically denies. Again like Hume's fork, the PSR conflates multiple distinctions and consequently eliminates important categories. Since the PSR incorrectly presupposes that those categories do not exist, the conclusions of its false premises are irrelevant.
        <br /><br />
        The contingency argument fundamentally confuses explanatory dependence with alethic modality. By stating that the universe is not necessary and therefore the universe is dependent, the contingency argument assumes that "dependent" means "not necessary," and that "independent" means "necessary." However, since "<Hyperlink to="https://www.reddit.com/r/DebateReligion/comments/eixcr4/the_argument_from_contingency_falls_in_on_itself/fcv6roz/">a contingent object has the same modal status as whatever it's contingent on</Hyperlink>," whether a thing's existence depends on other things' has nothing to do with whether that first thing exists necessarily or possibly. The word "contingent" is used for both, but "<Hyperlink to="https://www.reddit.com/r/DebateReligion/comments/eixcr4/the_argument_from_contingency_falls_in_on_itself/fcvbg4w">'Depends on other things' and 'can fail to exist' are not the same thing, regardless of if somebody at some point in the past made the foolish decision of using the same sounds/letters to refer to both</Hyperlink>."
        <br /><br />
        Dr. Craig replied to the use of abstract objects as PSR counterexamples by distinguishing different kinds of necessity: "<Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/the-leibnizian-cosmological-argument">[T]here might be things which exist in every possible world but are caused (numbers? moral values?). Still, such things would not exist by a necessity of their own natures even though they exist necessarily</Hyperlink>." Dr. Craig's version of the PSR says that everything "has an explanation of its existence (either in the necessity of its own nature or in an external cause)," seemingly accounting for the possibility of necessarily existent abstract objects which are explained by something else.
        <br /><br />
        Dr. Craig distinguished two types of necessity trying to rescue his<Note num={++notes}>Technically Stephen T. Davis’s, but I am responding to Craig's presentation/use of it.</Note> form of Leibniz's argument, but conflated two different kinds of dependence: causal and explanatory. Y causally depends on X just in case X brought Y into existence. In contrast, Y explanatorily depends on X just in case Y exists only if X exists. The difference is subtle, but it introduces at least two counterexamples to Craig's PSR:
        <ol>
            <li>In a block universe,<Note num={++notes}>By "block universe" I mean a universe where B-theory and eternalism are both true.</Note> one thing bringing another into existence does not happen. However, there may be something which only exists if another thing exists. In the block universe, human life is explanatorily dependent on the Sun, even though the Sun did not bring life into existence. If any kind of explanation is possible in a block universe, then explanatory dependence is not necessarily causal dependence.</li>
            <li>Abstract objects may depend on God for existence without being caused by God. If his existence necessarily implies theirs, then they non-causally depend on him. I explain this further in the next two paragraphs.</li>
        </ol>
        God did not simply invent the laws of logic, according to proponents of the TAG, but their existence depends on his. Matt Slick and Jason Lisle <Hyperlink to="https://carm.org/transcendental-argument">both said</Hyperlink> that the laws of logic <Hyperlink to="https://answersingenesis.org/world-religions/atheism/atheism-an-irrational-worldview/">"reflect" God's mind</Hyperlink>. In Lisle's terms, "The law of non-contradiction...stems from God’s self-consistent nature. God cannot deny Himself...so, the way God upholds the universe will necessarily be non-contradictory." God's existence implies that the noncontradiction law exists. Yet God did not cause that law to come into being. Instead, the law is a corollary of God's existence. That law reflects God and necessarily co-exists with him. So, it could only come into being if God came into being. Under this view, the laws of logic depend on God explanatorily but not causally.
        <br /><br />
        Further, God could not have decided to causally bring the laws of logic into being, because making a decision requires the laws of logic. Lisle said that "Laws of logic are God’s standard for thinking," so for God to think the laws of logic into being, he would first need those laws in order to think. So because there are other kinds of explanation than necessity of one's own nature and causal contingency, even Craig's weakened form of the PSR is false. 
        <br /><br />
        Christian apologists like Matt Bilyeu have used <Hyperlink to="https://rationalchristian.wordpress.com/2018/05/20/if-anything-exists-god-exists/">simplistic analogies to deny the possibility of self-explanatory contingent things</Hyperlink>:
        <blockquote>
        "Nothing just exists without a reason. If you are a parent and you come home to find a smashed vase in your living room, then you automatically assume that one of your children has broken the vase. The inference to some explanation for its being broken is automatic and obvious. If your child said, 'I don’t know, it just happened,' you would demand a better answer because you know better."
        </blockquote>
        Problems with using analogies to prove a point were already discussed. Also note that even if <em>most</em> things have a reason for existing in everyday experience, that does not negate the possibility of things existing without a reason or explanation outside of everyday experience. Again, the laws of nature and/or initial conditions of the universe may serve as examples. Intuitions formed from everyday experience cannot justifiably be exported as far outside of that experience as  cosmology and metaphysics, which describe the often unimaginably unintuitive fundamental nature of reality. One cannot infer from a child's broken vase that the universe requires an explanation because it is contingent.
        <br /><br />
        Either the PSR refutes itself, or it becomes so arbitrarily selective that it is no longer compelling, even as a so-called metaphysical first principle. Even ignoring that, the PSR conflates independent distinctions and consequently denies several categories of explanation outright. I unexpectedly stumbled onto these two PSR counterarguments while writing about the following one, which I consider far more compelling.
    </Section>
    <Section num={++sections} summary="According to the PSR, a thing is explained either by its nature or its cause. However, the traditional (Aristotelian essentialist) metaphysical definitions for both of these terms refer to nothing, and their (nominalist) modernist epistemic definitions entail brute facts.">
        Without mentioning that the PSR is self-refuting and arbitrarily denies relevant possibilities, examining what the PSR means by "explanation" can eliminate its persuasive force entirely. According to the PSR, a thing is explained either by its nature or its cause. However, the traditional (Aristotelian essentialist) metaphysical definitions for both of these terms refer to nothing, unlike their (nominalist) modernist epistemic definitions.
        <br /><br />
        First, consider a thing which is explained by its own nature. Traditionally, a thing's "nature" is its universal essence. However, there does not exist a universal essence. Nothing can then be explained by its own nature. Within a nominalist framework, a thing's "nature" is the set of necessary conditions which qualify it as a member of the category to which it is assigned by name. Things are ontologically prior to their categories, and therefore to the necessary conditions of categories. So, a thing's existence cannot be explained by its category's necessary conditions.
        <br /><br />
        Consider the implications if a thing could be explained by assigning it to a category. One could create the category "existents" of all existing things. Any member of that category must exist, since otherwise it would not be a member. Each member would then exist necessarily. According to the PSR, necessary things explain themselves. Either a thing has no nature, making it impossible for that thing to exist necessarily; or that thing's nature is assigned, making its existence necessary. If everything exists necessarily, then there is no need to explain anything's existence in terms of another thing. Therefore, there is no need to explain the universe's existence in terms of another thing.
        <br /><br />
        A thing's existence cannot be explained, then, by its nature. The two remaining options are to explain a thing by its cause or not to explain its existence at all. Quoting Douglas Groothius, Matt Bilyeu defined <Hyperlink to="https://rationalchristian.wordpress.com/2018/05/20/if-anything-exists-god-exists/">"contingency" as "the causal efficacy of other beings."</Hyperlink> Bilyeu also approvingly cited Dr. Craig's definitions of "necessary beings, which … exist of their own nature and so have no external cause of their existence, and contingent beings, whose existence is accounted for by causal factors outside themselves."<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 107.</Note> In short, they all say that the explanation of a contingent thing is its cause.
        <br /><br />
        The defender of the PSR must equate explanation with causality to reject the possibility of multiple contingent beings explaining each other. If this possibility is admitted, then the need for a necessary being disappears: there could be a circle of contingent beings explaining each other, and all other beings could be indirectly contingent on that circle. Imagine that A explains B, B explains C, C explains A, and everything else is contingent on either A, B, or C. No necessary being would be required. Invoking unidirectional causality excludes that possibility.
        <br /><br />
        Causality is either external to the mind and therefore a metaphysically real process, or internal and therefore an epistemic predictive heuristic. The first is the traditional definition introduced by Aristotle, while Hume introduced the second. Consider each in turn.
        <br /><br />
        For the first, eternalism negates the PSR. A contingent thing's explanation is its efficient cause — the thing which brought it into being. In this case, the contingency argument folds into the KCA, and the same response applies: efficient causality does not exist because all things in any moment of time exist actually, and therefore need no efficient cause to bring them from potential to actual existence. The existence of each thing is then a brute fact, including the universe itself. If an explanation is an efficient cause, then the PSR is <em>completely</em> false: <em>nothing</em> has an explanation of its existence.
        <br /><br />
        For the second, empiricism negates the PSR. According to Hume, causality is the constant conjunction of observations: when observing one thing consistently precedes observing another, people say that the former thing causes the latter thing. Since it requires observation, causality exists only in the mind. The explanation of a thing's existence is then whatever preceding observations(s) allow one to predict the existence of the thing. One can explain those observation(s) in terms of (an)other prior observation(s), leading to another trilemma: observations extend backwards forever, terminate in a necessary observation, or terminate in a brute fact observation. The first is impossible unless one has lived through every moment of an infinite past. The second is either incoherent or absurd unless it folds into the third: since each person has had a first observation, a thing's chain of explanations must eventually terminate at (a) prior unexplained observation(s). Unexplained observations negate the PSR.
        <br /><br />
        Either brute facts or false conclusions follow from explaining a thing's existence by appealing to its nature or its cause. Brute facts are inevitable. Since the PSR denies brute facts, it is false even if one ignores its aforementioned self-refutation and conflation.
        <br /><br />
        Dr. Craig has accused some atheists of using the <Hyperlink to="https://www.reasonablefaith.org/question-answer/P40/questions-about-leibnizs-cosmological-argument">so-called "Taxicab Fallacy"</Hyperlink> by "arbitrarily dismissing the Principle of Sufficient Reason once one has arrived at one’s desired destination" when they assert that the universe does not require an explanation of its existence. Recall that a fallacy is a structural flaw in a deductive argument such that the conclusion does not follow necessarily from the premises. The "Taxicab Fallacy" is simply a name for atheists rejecting Craig's preferred metaphysical assumptions, so it is not a deductive invalid argument structure. It is no fallacy at all. To call it a fallacy as Craig does is dishonest. And again, explaining things in terms of the laws of nature and the universe's initial conditions allows one to coherently say that the universe does not need an explanation of its existence.
    </Section>
    <p>One of the most common objections to Leibniz's contingency argument that I have encountered, despite its commonality, is not quite sufficient to refute the contingency argument on its own:</p>
    <Section num={++sections} summary="If existence exists necessarily, then showing that each thing in the universe exists contingently would not entail that the universe itself exists contingently. But claiming that existence necessarily exists is unjustified.">
        Perhaps ironically, it seems that another mistake made by theists who use Leibniz's contingency argument is reductionism: the attribution of some quality of a part to its whole. Consider some whole, <em>X</em>, and its parts, <em>x</em>, with the question of whether or not they have some trait, <em>y</em>: For any <em>x</em> in <em>X</em>, it is not the case that if some trait <em>y</em>applies to all <em>x</em>, then it necessarily applies to <em>X</em>. In symbolic logic, ∀<em>x</em>(<em>x</em> ∈ <em>X</em>): ¬(∀<em>x</em>∃<em>y</em> ⇒ <em>X</em>(∃<em>y</em>)). If everything in the universe exists contingently, that does not entail that the universe exists contingently.
        <br /><br />
        The contingency argument asserts that the contingency of parts proves the contingency of the whole. <Hyperlink to="http://www.biblicalcatholic.com/apologetics/p20.htm">Friar Copleston straightforwardly admitted as much</Hyperlink> when he used the contingency argument in his 1948 debate with Bertrand Russell:
        <blockquote>
        "I don't believe that the infinity of the series of events -- I mean a horizontal series, so to speak -- if such an infinity could be proved, would be in the slightest degree relevant to the situation. If you add up chocolates you get chocolates after all and not a sheep. If you add up chocolates to infinity, you presumably get an infinite number of chocolates. So if you add up contingent beings to infinity, you still get contingent beings, not a Necessary Being."
        </blockquote>
        Like Copleston, Dr. Craig <Hyperlink to="https://www.reasonablefaith.org/question-answer/P40/argument-from-contingency/">also tried to justify the reductionism of the contingency argument</Hyperlink> by using an analogy:
        <blockquote>
        "Imagine that you’re hiking through the woods one day and you come across a translucent ball lying on the forest floor. You would naturally wonder how it came to be there. If one of your hiking partners said to you, 'It just exists inexplicably. Don’t worry about it!', you’d either think that he was crazy or figure that he just wanted you to keep moving. No one would take seriously the suggestion that the ball existed there with literally no explanation. Now suppose you increase the size of the ball in this story so that it’s the size of a car. That wouldn’t do anything to satisfy or remove the demand for an explanation. Suppose it were the size of a house. Same problem. Suppose it were the size of a continent or a planet. Same problem. Suppose it were the size of the entire universe. Same problem. Merely increasing the size of the ball does nothing to affect the need of an explanation."
        </blockquote>
        In his analogy, Craig conflates "size" with "having more parts," although that is forgivable since larger objects are usually composed of more atoms.
        <br /><br />
        These ostensibly harmless analogies actually lead to a denial of the existence of emergent properties. One can imagine all kinds of situations where new properties emerge from a system due to it having many or more components. Even in Craig's example, as the ball grew larger it would change quite a bit due to its increased size, gaining properties that it lacked at its smaller size. As another example, culture does not emerge from one person but from many people. Even though no one person has a culture, a culture emerges from the interactions between many people.
        <br /><br />
        Those examples, though, are insufficient because the number of people in any group(s) differs by degree whereas there is a binary distinction between contingency and necessity. Nothing can be more contingent than something else or half-necessary. Also, every emergent property is generally thought to be ontologically posterior to whatever thing(s) emerges from. Presumably something necessary cannot be posterior to something contigent, which is another problem with those examples.
        <br /><br />
        <Hyperlink to="http://www.biblicalcatholic.com/apologetics/p20.htm">Russell provided a better example</Hyperlink> in the aforementioned debate:
        <blockquote>
        "I can illustrate what seems to me your fallacy. Every man who exists has a mother, and it seems to me your argument is that therefore the human race must have a mother, but obviously the human race hasn't a mother--that's a different logical sphere."
        </blockquote>
        The fallacy of arguing from parts to a whole, which Copleston and Dr. Craig used and Russell exposed, is known as the fallacy of composition. The trait(s) of the whole cannot necessarily be inferred from the trait(s) of the part(s), and vice versa. Hence, one apparently cannot infer that the universe is contingent merely because all parts of the universe are contingent.
        <br /><br />
        If one accepts the PSR's category distinctions, though, then the only alternative to calling the universe contingent is to call it metaphysically necessary — in other words, the universe could not have failed to exist. Without any evidence or argument(s) to justify this metaphysical assertion, Ockham's razor would call it metaphysically egregious. If this objection merely <em>questions</em> that the universe is <em>not</em> metaphysically necessary, then it would lose in strength whatever it may gain in plausibility. It could not then deny the PSR, implying agnosticism about it at most.
        <br /><br />
        Still, the objections presented to Leibniz's cosmological argument could be presented here to support the metaphysical necessity of the universe — that is, of existence. As St. Bonaventure said, "being itself is so certain in itself that it cannot be thought not to be." If anything necessarily exists, it must be existence itself: necessarily, existence exists. If existence necessarily exists, then according to the PSR, it is self-explanatory.
        <br /><br />
        I hesitate to endorse this objection for several other reasons. I would rather do away with metaphysical modality entirely, refusing to call anything metaphysically necessary or possible except to expose flaws in others' arguments. And even if one can use the language of metaphysical necessity, it may be an illicit move to say that existence exists necessarily, because perhaps the set of all existing things could simply be empty. But while this argument has its flaws, it would refute the PSR if one could show that existence exists necessarily and therefore requires no explanation.
    </Section>
  </Layout>
);

export default ConLeibniz;