import React from "react"
import { Link } from "gatsby"
import Hyperlink from "../components/Hyperlink"
import Section from "../components/Section"
import Note from "../components/Note"

import Layout from "../components/layout"
import SEO from "../components/seo"

var notes = 0;
var sections = 0;
const CosCraig = () => (
  <Layout>
    <SEO title="William Lane Craig's Kalam Cosmological Argument" />
		<p>Dr. William Lane Craig's most well-known argument is the "kalām cosmological argument" (KCA):
		<ol>
			<li>Whatever begins to exist has a cause.</li>
			<li>The universe began to exist.</li>
			<li>Therefore, the universe has a cause.</li>
		</ol>
		Two main criticisms of the KCA will be discussed in detail here. Argument 1 criticizes the epistemology of the KCA to show that its first premise is not necessarily true. Argument 2 uses empirical evidence to refute the metaphysical presuppositions of premise 2 of the KCA.
			<Section num={++sections} summary="Premise 1 of the KCA is based on the assumptions that 'nothing comes from nothing' and that causality is universal, which are not necessarily true.">
				<blockquote>"<em>Concepts that have proven useful in ordering things easily achieve such authority over us that we forget their earthly origins and accept them as unalterable givens. Thus they might come to be stamped as "necessities of thought," "a priori givens," etc. The path of scientific progress is often made impassable for a long time by such errors. Therefore it is by no means an idle game if we become practiced in analysing long-held commonplace concepts and showing the circumstances on which their justification and usefulness depend, and how they have grown up, individually, out of the givens of experience. Thus their excessive authority will be broken. They will be removed if they cannot be properly legitimated, corrected if their correlation with given things be far too superfluous, or replaced if a new system can be established that we prefer for whatever reason."</em>
				<br />
				–Albert Einstein<Note num={++notes}>From Einstein's "Obituary for physicist and philosopher Ernst Mach (Nachruf auf Ernst Mach), Physikalische Zeitschrift 17 (1916), p. 101," found on <Hyperlink to="https://en.wikiquote.org/wiki/Albert_Einstein">Albert Einstein's Wikiquote.</Hyperlink></Note></blockquote>
				The first premise of the KCA dubiously assumes that causality is universal. Some skeptics have protested the assumed universality of causation by pointing out the existence of <Hyperlink to="http://rationalwiki.org/wiki/William_Lane_Craig#Why_the_Kal.C4.81m_Cosmological_Argument_fails">quantum phenomena that have no apparent cause</Hyperlink>, like quantum tunnelling and radioactive decay. Dr. Craig responded by pointing out that such phenomena are only <Hyperlink to="http://onlinelibrary.wiley.com/doi/10.1002/9781444308334.ch3/summary">causeless under indeterministic interpretations of quantum mechanics</Hyperlink> like the Copenhagen interpretation, and subsequently rejecting such interpretations. 
				<br /><br />
				Regarding quantum phenomena, <Hyperlink to="https://beliefmap.org/god-exists/first-cause/uncaused-events/#quantum">Blake Giunta responded by claiming</Hyperlink> that such phenomena are "caused <em>indeterministically</em>" and "certainly did not come <em>from nothing</em>." If the first response is correct, then there exists an efficient cause of quantum phenomena, but no such cause is evident - unless Giunta believes that Chance is some metaphysically real force of nature that causes all of the randomness in the universe. The second response conflates the argument from causeless phenomena with the argument that something can come from nothing because the energy of the quantum vacuum produces virtual particles.<Note num={++notes}>I call it "Krauss equivocation." See the end of the KCA section for a brief description.</Note> The argument that quantum phenomena lack an <em>efficient</em> cause cannot be rebutted by pointing out their <em>material</em> cause.
				<br /><br />
				Relying on a classic burden-of-proof-shifting maneuver, Peter Kreeft said to "hang on a second," since "<Hyperlink to="https://www.prageru.com/videos/god-vs-atheism-which-more-rational">Just because scientists don’t see a cause, doesn’t mean there isn’t one."</Hyperlink> It also does not mean that there <em>is</em> one. What it <em>does</em> mean is that people should not make the unfounded assertion that one exists, as Kreeft does.
				<br /><br />
				Dr. Craig has provided <Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/causal-premiss-of-the-kalam-argument">three justifications for premise 1 of the KCA</Hyperlink>:
				<blockquote>"First and foremost, the causal premiss is rooted in the metaphysical intuition that something cannot come into being from nothing. To suggest that things could just pop into being uncaused out of nothing is to quit doing serious metaphysics and to resort to magic. Second, if things really could come into being uncaused out of nothing, then it becomes inexplicable why just anything and everything do not come into existence uncaused from nothing. Finally, the first premiss is constantly confirmed in our experience, which provides atheists who are scientific naturalists with the strongest of motivations to accept it."</blockquote>
				In this description Dr. Craig claims that the first justification is an <em>a priori</em> metaphysical first principle, but the second and third are based on observational experience. Craig's statement that "something cannot come into being from nothing" originates from the statement that <Hyperlink to="https://en.wikipedia.org/wiki/Nothing_comes_from_nothing">out of nothing, nothing comes</Hyperlink> in <em>De Retum Natura</em> ("On the Nature of Things"), the only known work of the Roman Epicurean philosopher Lucretius — and notably, it is not necessarily true. Its denial entails no contradictions, and when Craig asks us to imagine something coming from nothing to show its absurdity, he acknowledges that something coming from nothing is conceivable. Because its denial is conceivable and entails no contradictions, "something coming from nothing" is "<Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/causal-premiss-of-the-kalam-argument">strictly logically possible</Hyperlink>," as Craig has acknowledged. In other words, Craig's claim that it is metaphysical impossible is based neither on logical necessity nor empirical observation. What, then, is its basis? Craig <em>merely asserts</em> it to be true based on his "metaphysical intuition," also known as his personal feelings.
				<br /><br />
				Blake Giunta objected to this characterization of Dr. Craig's metaphysical principle, and claimed that something can be <Hyperlink to="https://beliefmap.org/metaphysics/uncaused-events/#consistent">metaphysically impossible even if it is noncontradictory</Hyperlink>:
				<blockquote>"Consider the proposition that <em>the color purple weighs three pounds</em>. This proposition may not yield a formal logical contradiction, but it is nevertheless impossible. It is worth nothing that some beliefs are rightly basic belief; they do not require evidence or demonstration."</blockquote>
				He is correct that the proposition is indeed metaphysically impossible, but that can be shown without resorting to "rightly basic beliefs." The proposition attributes color, a property of a physical object, to something that is not a physical object — namely weight, which is another property of a physical object — and is therefore incoherent. One cannot imagine any possible world where a property like color has a property like weight. Even though one can imagine a world where all purple objects weigh three pounds, it is still those objects themselves rather than their color which have weight. In context, this is a poorly chosen example because the possibility of something coming from nothing is meaningful and conceivable. Again, how could one show that something coming from nothing is metaphysically impossible <em>a priori</em>?
				<br /><br />
				Dr. Craig claims that even David Hume "clearly believed in the causal principle," since Hume said that "I never asserted so absurd a Proposition as that anything might arise without a cause."<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 113.</Note> Craig papers over an important distinction, however: Hume never <em>asserted</em> that something can come from nothing, but he did not <em>deny</em> it either. As one would expect from the proto-verificationist, Hume had a very skeptical view of Craig's "metaphysical principle":
				<blockquote>"That impious maxim of the ancient philosophy, <em>Ex nihilo, nihil fit</em>, by which the creation of matter was excluded, ceases to be a maxim, according to this philosophy. Not only the will of the supreme Being may create matter; but, for aught, we know a priori, the will of any other being might create it, or any other cause, that the most whimsical imagination can assign."<Note num={++notes}>Hume, <em>An Enquiry Concerning Human Understanding</em>, p. 107.</Note></blockquote>
				While Dr. Craig conceded that one can imagine something coming from nothing, he still thinks that it is metaphysically impossible because it seems absurd.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 113.</Note> Since the set of physically possible things is a subset of the set of metaphysically possible things, claiming that something is metaphysically impossible is a much stronger claim than claiming that it is physically impossible. And since a significant weight of empirical evidence is needed to demonstrate the physical impossibility of a thing, the evidence to demonstrate the metaphysical impossibility of a thing should be even stronger. Intuitive impressions are simply insufficient to justify a metaphysical principle.
				<br /><br />
				Basing the second and third justifications for the KCA on experience may seem in Craig's mind to give them more credence to scientific naturalists, but it actually provides a basis to dismiss them: we have never observed anything begin to exist. Any physical thing that we have observed is formed out of pre-existing matter and energy. By claiming that matter "begins to exist" if it merely changes its physical form, Craig uses the phrase "begins to exist" in two ways: things that we observe "begin to exist" out of other pre-existing physical things, while the universe apparently "began to exist" out of nonbeing, literally nothing.
				<br /><br />
				In a Biola University lecture where he attempted to address what he considered the "10 Worst Objections to the Kalam Argument," Dr. Craig claimed to provide a "univocal definition" of "begins to exist" which is "adequate for all practical purposes" and resolves the problem of equivocation: <Hyperlink to="https://youtu.be/sfsYhWNMYr4?t=33m22s">"<em>x</em> begins to exist if and only if <em>x</em> exists at time <em>t</em> and there is no time <em>t*</em> prior to <em>t</em> at which <em>x</em> exists."</Hyperlink> But the equivocation problem remains. If all of the matter and energy which <em>x</em> is composed of exists at <em>t</em>*, does <em>x</em> still begin to exist at <em>t</em>? <Hyperlink to="http://commonsenseatheism.com/?p=15736">This shows a categorical difference</Hyperlink> between the way that the universe does not have a preceding time and the way that anything else does not have a preceding time, since Craig "wants to use intuitions about one type of 'beginning to exist' and apply them to this new, different, unique type. But he can’t just come out and admit that because it would weaken his argument to admit that there are categorical differences in these two situations, so he buries it under verbiage."
				<br /><br />
				Dr. Craig considers this difference irrelevant to the soundness of the KCA.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 155.</Note> However, he cannot use observations of <em>something changing its form out of pre-existing matter</em> to justify the universe <em>beginning to exist without any pre-existing matter or energy</em>, because an atheist could affirm a different principle that <em>any state change of matter or energy has a cause</em> while denying – or withholding their assent from – the first premise of the KCA.
				<br /><br />
				In a debate with Christopher Hitchens, Christian apologist Frank Turek attempted to invoke the KCA by claiming that there must have been a cause for the universe "<Hyperlink to="https://youtu.be/NSqnl22Onzw?t=2m3s">to go from a state of non-existence to a state of existence."</Hyperlink> If it worked, this would be justified by the principle that any state change has a cause. However, it is incoherent: there has never been and could never be a "state of non-existence" because it is logically impossible that a nonexistent thing exists in a state. Turek's description is contradictory. <Hyperlink to="https://youtu.be/NSqnl22Onzw?t=2m50s">Change is inherently temporal</Hyperlink> because change is a transition from one state to another and any transition must happen in time; otherwise, it would not have any time to transition. Since no change took place at the first "state of existence" of the universe, one cannot conclude that it had a cause under the principle that any state change of matter or energy has a cause.
				<br /><br />
				Refusing to grant the first premise of the KCA would not necessarily be "<Hyperlink to="https://www.reasonablefaith.org/media/reasonable-faith-podcast/the-best-of-the-kalaam-cosmological-argument">literally worse than magic,</Hyperlink>" as Craig has argued. It would merely express skepticism at our ability to make sweeping, universal statements about physical reality based on our feelings and two-thousand-year-old metaphysics without any physical evidence or logically necessary deductions — especially when the evidence suggests otherwise.
				<br /><br />
				Dr. Craig has based his KCA on the fact that the universe is expanding. In other words, the universe at one moment contains more space than it did at a previous moment. The universe's expansion is caused by dark energy, represented by the cosmological constant. Since its density is constant, dark energy does not expand as the universe grows. Instead, more of if it is created — from nothing. New dark energy has no efficient cause, so it comes from nothing. The law of conservation of energy only applies in a Newtonian static universe, but energy can be gained or lost in a relativistic expanding universe. The supposedly universal and metaphysically necessary principle that nothing comes from nothing has technically already been falsified.
				<br /><br />
				The aforementioned Biola lecture example is not the only problem with Dr. Craig's definition of beginning to exist. If "<em>x</em> begins to exist if and only if <em>x</em> exists at time <em>t</em> and there is no time <em>t</em>* prior to <em>t</em> at which <em>x</em> exists," then God began to exist. God existed at time <em>t</em> = 0 and there was no time <em>t</em>* prior to <em>t</em> at which God existed. Under this definition alone, God "began to exist" in the exact same sense that the universe "began to exist." If God began to exist, then the age-old question guaranteed to annoy any theist suddenly becomes legitimate again: who or what caused God?
				<br /><br />
				To fix this problem, Dr. Craig <Hyperlink to="https://youtu.be/sfsYhWNMYr4?t=34m25s">amended his definition of "begins to exist"</Hyperlink> by adding a new phrase:
				<blockquote>"<em>x</em> begins to exist if and only if <em>x</em> exists at time <em>t</em> and there is no time <em>t</em>* prior to <em>t</em> at which <em>x</em> exists and no time <em>t</em>* prior to <em>t</em> at which <em>x</em> exists and no state of affairs in the actual world in which <em>x</em> exists timelessly."</blockquote>
				One wonders how long and complicated Dr. Craig is prepared to make his definition before giving up the KCA entirely, especially since his new definition "<Hyperlink to="http://rationalwiki.org/wiki/William_Lane_Craig#Who_created_God.3F">seems to serve the sole purpose of creating a God-shaped hole into which Craig can slot his preferred deity."</Hyperlink> However, the long and convoluted back-and-forth which emerged over whether God's timeless nature is compatible with the KCA has not produced a clear counterargument to the KCA, as will be discussed after the sound counterarguments.
			</Section>
			<Section num={++sections} summary="The KCA's definition of 'begins to exist' presupposes presentism and the A-Theory of time, which have been discredited because the relativity of simultaneity shows that the present moment only exists relative to an observer's reference frame.">
				A month after his Biola lecture, Craig <Hyperlink to="https://www.reasonablefaith.org/question-answer/P20/beginning-to-exist">clarified his definition of "begins to exist" by extending it even further</Hyperlink> while answering a question on his website:
				<blockquote>"The kalam cosmological argument uses the phrase 'begins to exist.' I sometimes use the expression 'comes into being' as a synonym. We can explicate this last notion as follows: for any entity <em>e</em> and time <em>t</em>, <em>e</em> comes into being at <em>t</em> if and only if (i) <em>e</em> exists at <em>t</em>, (ii) <em>t</em> is the first time at which <em>e</em> exists, (iii) there is no state of affairs in the actual world in which <em>e</em> exists timelessly, and (iv) <em>e</em>’s existing at <em>t</em> is a tensed fact."</blockquote>
				Let's explore the <Hyperlink to="https://www.reasonablefaith.org/question-answer/P20/beginning-to-exist">consequences of the phrase "tensed fact"</Hyperlink> that Dr. Craig has appended onto his definition, in his own words:
				<blockquote>"[I]f there are tensed facts, then time itself is tensed. That is to say, the moments of time are really past, present, or future, independently of our subjective experience of time ... The reality of tensed facts therefore entails a tensed theory of time, usually called an A-Theory of time ... on a tenseless or B-Theory of time there really are no tensed facts ... in objective reality there is no 'now' in the world. Everything just exists tenselessly. So according to the B-Theory of time, all things and events in time are equally existent ... Nothing in the space-time block ever comes into or goes out of being, nor does the space-time block as a whole come into being or pass away ... The kalam cosmological argument presupposes from start to finish an A-theory of time ... On a B-Theory of time ... [t]he universe began to exist only in the sense that the tenselessly existing block universe has a front edge. It has a beginning only in the sense that a yardstick has a beginning ... Clause (iv) of my explication is an expression of my endorsement of an A-Theory of time and the reality of temporal becoming."</blockquote>
				The KCA's veracity is contingent on that of the A-theory of time. If A-theory is false or unsupported, so too is the KCA. If B-theory is shown to be true, then the KCA fails because there is no need for the universe to have a cause. Dr. Craig's "yardstick" analogy can help to explain why it is not necessarily true given B-theory that prior events cause posterior events: there is no reason to claim that the first inch on a yardstick "causes" the second inch.
				<br /><br />
				Even if the past is finite, one cannot infer that the beginning of the universe was a <em>tensed fact</em> because a finite past is possible given B-theory. Dr. Craig's arguments for the finitude of the past are therefore irrelevant to the B-theory objection to the KCA, because (by definition) the universe only began to exist if its beginning was a tensed fact. If its beginning was a tenseless fact, then the future already existed tenselessly, with no need for some cause to initiate its existence.
				<br /><br />
				On his website, Dr. Craig said that it seems nice for some people to give arguments that the causal principle applies under B-theory, but those arguments <Hyperlink to="https://www.reasonablefaith.org/question-answer/P50/gods-necessity-and-the-causal-principle-on-a-b-theory-of-time">"fall far below the metaphysical grounds which the A-theorist can offer in justification of the principle, namely, that something cannot come into being from nothing."</Hyperlink> In other words he recognizes that if B-theory is correct, then it is not metaphysically necessary that prior events cause posterior events. He likes that some people try to come up with justifications for the causal principle under B-theory, but realizes that attempted justifications for a B-theoretic causal principle will not be metaphysically necessary.
				<br /><br />
				Another article that Dr. Craig wrote described fairly well why the causal principle does not apply to B-theory. It pointed out that <Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/does-the-b-theory-of-time-exclude-human-freedom">"B-theory does not imply that events which lie in our future are causally determined with respect to antecedent events"</Hyperlink> and "some such event could be wholly undetermined by antecedent causes." In other words, the principle that posterior events are caused by prior events does not necessary apply to a B-theory block-universe. The beginning of the universe could be an event "wholly undetermined by [logically/explanatorily] antecedent causes," implying an uncaused universe.
				<br /><br />
				As Sean Carroll explained in his debate with Dr. Craig, <Hyperlink to="https://www.reasonablefaith.org/media/debates/god-and-cosmology-the-existence-of-god-in-light-of-contemporary-cosmol#presentation-3">"the way physics is known to work these days is in terms of patterns, unbreakable rules, laws of nature"</Hyperlink> instead of temporally connected causes and effects. For that debate, Craig had actually changed the KCA's wording to "(1) if the universe began to exist, then it has a transcendent cause; (2) the universe began to exist; (3) the universe has a transcendent cause." He did this because <Hyperlink to="https://www.reasonablefaith.org/question-answer/P90/some-reflections-on-the-sean-carroll-debate">he realized that the older KCA "presupposes an Aristotelian conception of causality, according to which substances stand in causal relations to one another."</Hyperlink> The new KCA formulation would still fail if B-theory is true because, under B-theory, the universe did not <em>begin to exist</em> since its beginning was not a tensed fact.
				<br /><br />
				Incidentally, the biggest KCA-related misunderstanding in the Carroll-Craig debate was that Dr. Craig presupposed A-theory and Carroll presupposed B-theory. To his credit, <Hyperlink to="https://www.reasonablefaith.org/media/debates/god-and-cosmology-the-existence-of-god-in-light-of-contemporary-cosmol#presentation-8">Craig pointed this out himself in the post-debate Q&A</Hyperlink>:
				<blockquote>"I do want to take this opportunity to highlight for you a very significant difference between Sean and myself that is a philosophical difference that has tremendous impact upon this whole debate ... Dr. Carroll holds to what is called a tenseless theory of time. That is to say, past, present, and future events are all equally real. Temporal becoming is merely a subjective illusion of human consciousness ... I hold to quite a different view of time. I think that temporal becoming is a real and objective feature of the universe. The future doesn't in any sense exist; things really do come into being and go out of being. And that's why I use the language of popping into existence. Not because I illicitly presuppose time prior to the origin of the universe, but because I believe in a tensed theory of time which affirms the objectivity of temporal becoming. And on that view the beginning of the universe does not just tenselessly exist. The universe comes into being, and surely that requires a cause ... this is a huge metaphysical assumption that underlies this debate and divides us."</blockquote>
				Curtis Metcalfe has <Hyperlink to="https://irl.umsl.edu/cgi/viewcontent.cgi?referer=https://www.google.ca/&httpsredir=1&article=1186&context=thesis">argued that the KCA works even given B-theory</Hyperlink> because an entity can still be said to "begin to exist" if that entity exists at time t but not before. His rephrasing is irrelevant because B-theory makes it false that whatever exists at a point in time but not before has an efficient cause. Recall that an efficient cause of <em>x</em> moves <em>x</em> from potential to actual existence. Given B-theoretic eternalism, all entities in any moment of time exist actually rather than potentially. Therefore, no entity has an efficient cause given B-theoretic eternalism. In a similar vein, Andrew Loke <Hyperlink to="https://s3.amazonaws.com/academia.edu.documents/32580173/repo_A91Sg8uI.pdf?AWSAccessKeyId=AKIAIWOWYYGZ2Y53UL3A&Expires=1527760951&Signature=eGrbbP%2F%2FdcUO5znZ9%2BIp0ysrsqM%3D&response-content-disposition=inline%3B%20filename%3DLoke_Andrew._2014_._A_MODIFIED_PHILOSOPH.pdf">also tried to make a B-theoretic KCA</Hyperlink>. It concludes with, "Therefore, it is not metaphysically possible that time is beginning-less." Again, even if Loke is entirely correct, a first moment in time requires no efficient cause to bring it into being given B-theoretic eternalism. Both authors simply missed the point.
				<br /><br />
				While reflecting on his debate with Sean Carroll, Dr. Craig <Hyperlink to="https://www.reasonablefaith.org/question-answer/P90/some-reflections-on-the-sean-carroll-debate">tried to rephrase one of his arguments for his causal principle in B-theoretic terms</Hyperlink>:
				<blockquote>"[I]f something can come into being without a cause, then it becomes inexplicable why anything and everything does not do so. Carroll might try to avoid this argument by appealing once again to a tenseless theory of time. But it is not evident that this argument will not also work even on a tenseless theory. One may simply re-phrase it to remove any reference to temporal becoming: if something can begin to exist without a cause, then it becomes inexplicable why anything and everything does not do so."</blockquote>
				First note the failure to remove the assumption of temporal becoming: given B-theory, nothing begins to exist. In fairness to Dr. Craig, his argument can be fixed: If something can have a first moment in time without a cause existing before that moment, one might argue, then it becomes inexplicable why anything and everything does not do so. Yet even if he had used this fixed argument, Craig willingly ignored the naturalistic definition of causality which Carroll explicitly mentioned earlier in the reflection: "Carroll explains that in physics causal explanations are given in terms of laws of nature (and, presumably, initial conditions), and so in the case of a beginning of the universe there cannot be such an explanation, since there are no prior conditions on which the laws of nature impinge." Carroll's definition of causality makes it quite explicable why anything and everything does not have a first moment in time without a cause existing before that moment: it would violate the laws of nature.
				<br /><br />
				Dr. Craig had mentioned Carroll's definition of causality in an attempt to refute it. He claimed that it only applies to physical causes but not metaphysical ones, so "the question remains, why did the universe come into being? Apart from a metaphysical, transcendent cause, you’re stuck with the universe’s popping into being uncaused." Again, given B-theory, "the universe begins to exist at the Big Bang only in the sense that … it has a front edge, so to speak, but it really does not come into being." It therefore requires no transcendent cause. Craig called A-theory his "trump card for defending the causal premiss." Conversely, B-theory is a "trump card" to reject it.
				<br /><br />
				Even without considering modern cosmology, Dr. Craig has tried to disprove the possibility of an eternal universe through metaphysics alone by claiming that an actual infinity cannot exist, and that therefore time cannot actually be infinite in the past.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 116.</Note> Craig does not specify what kind of actual infinity cannot exist, though, since "infinity" refers not to a single numerical quantity but a category of numerical quantities. Incidentally, that is the main problem with the thought experiment he uses to try to disprove actual infinities, Hilbert's Hotel: it equivocates multiple different quantities which are both called "infinity."
				<br /><br />
				As William of Ockham recognized, presentism prohibits rejecting an infinite causal chain based on the impossibility of an actual infinity: "<Hyperlink to="https://www.iep.utm.edu/ockham/#SH6bii">Since the links in the chain would not all exist at the same time, they would not constitute an uncountable quantity of actually existing things."</Hyperlink> Perhaps ironically, Craig's rejection of actual infinities could only apply under B-theory if that rejection is coherent.
				<br /><br />
				Dr. Craig claimed that infinity <Hyperlink to="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-kalam-cosmological-argument/">"<em>is</em> a number, the number of elements in the set [0, 1, 2, 3, . . . ]"</Hyperlink> in modern mathematics, but <Hyperlink to="https://youtu.be/SrU9YDoXE88?t=1m15s">"infinity is not a number, it's a <em>kind</em> of number"</Hyperlink> such that "you need 'infinite numbers' to talk about and compare amounts that are unending" because "some unending amounts — some infinities — are literally bigger than others." For example, aleph null is an infinity, but it is smaller than the infinity called aleph one. Since Dr. Craig has <Hyperlink to="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-kalam-cosmological-argument/">acknowledged that actual infinities do not entail any logical contradictions</Hyperlink>, he must realize that there are different numbers which are the type of number called "infinity."
				<blockquote>"Addition and subtraction of <em>numbers</em> is one thing; constructing a new set by adding in new members or removing old ones is quite a different thing. Operations of the second sort may be possible even when operations of the first sort make no sense or are undefined. It is only by confounding the two sorts of operation that Craig can imagine that he has derived a ‘logical contradiction’ from the actual infinite."<Note num={++notes}>Wes Morriston, <Hyperlink to="http://spot.colorado.edu/~morristo/craig-on-the-actual-infinite.pdf">"Craig on the Actual Infinite,"</Hyperlink> p. 6.</Note></blockquote>
				Morriston also argued that because events are fixed in time, Hilbert's Hotel is disanalogous to an actually infinite number of events by presupposing that people can switch rooms. Dr. Craig <Hyperlink to="https://www.reasonablefaith.org/media/reasonable-faith-podcast/the-best-of-the-kalaam-cosmological-argument">responded by phrasing Hilbert's Hotel modally</Hyperlink> such that the people are all locked in their rooms but one can imagine what it would be like if they switched rooms. Translated through the analogy, Craig argued that one can imagine events in time switching places and "generate the same absurdities" as Hilbert's Hotel.
				<br /><br />
				An actual infinity may seem absurd to Dr. Craig, but how does he justify his claim that it is absurd? He does not use mathematical logic, because Cantorian set theory has demonstrated that an infinite set entails no contradictions. He does not use the laws of physics. Instead, he appeals to metaphysical intuition, that ancient and apparently unquestionable basis for synthetic <em>a priori</em> beliefs. However, one cannot trust intuition to accurately describe areas as far outside of everyday experience as the properties and possibilities of infinities. System 1's accuracy in dealing with everyday situations allows metaphysical analyses of everyday situations to appeal to intuition with some legitimacy – associations in a stable environment can reliably describe their environment. But if one attempts to apply those associations outside the environment in which they were formed, they are unreliable. It is dubious for Dr. Craig to suggest that intuition, which is nothing more than associations, can conclusively rule out the possibility that a noncontradictory concept is instantiated in reality.<Note num={++notes}>One may object that I equivocate metaphysical intuition with associative processes in the mind, and argue that there is some conceptual distinction between the two. However, I am aware of no such distinction. Even if a conceptual distinction exists, I am aware of no evidence that it applies to reality: associative processes are mistakenly identified as metaphysical intuition. I suspect that the intuition which the ancients used to justify their commonsense beliefs is nothing more than the associative processes of the mind.</Note>
			</Section>
		So the KCA is insufficient to show that God exists, poor objections notwithstanding. Before moving on from the KCA, though, it may be prudent to discuss the problems with several of its weakest objections. I considered including many if not all of these in the previous section until I examined them further and discovered why they are problematic. They do not contribute to the overall thesis, however, so unless you are curious about which counterarguments to the KCA fail you may safely ignore the following section. The arguments are included to clarify why I am not using them, and if possible to correct atheists who use them without being aware of their flaws.</p>
			<Section num={++sections} summary="Because 'the quantum vacuum' differs from 'nothing,' something coming from the quantum vacuum does not show that something can come from nothing.">
				Some atheists have argued that the first premise of the KCA has been falsified by the existence of virtual particles, which are ostensibly <Hyperlink to="http://thesecularatheist.com/argument_from_motion.html">"created (and annihilated) all the time out of literally nothing."</Hyperlink> To do so, <Hyperlink to="https://youtu.be/0qCa0-aah1k?t=11m48s">several of them</Hyperlink> have <Hyperlink to="http://www.atheismandthecity.com/2012/09/refuting-william-lane-craig-kalam.html">cited</Hyperlink> Dr. Lawrence Krauss, who <Hyperlink to="https://www.reasonablefaith.org/media/debates/the-craig-krauss-debate-at-north-carolina-state-university#presentation-3">used that argument against the KCA</Hyperlink> in a debate with Dr. Craig:
				<blockquote>"In fact, one of the things about quantum mechanics is, nothing—not only can nothing become something, nothing always becomes something. Nothing is unstable. Nothing will always produce something in quantum mechanics. And if you apply quantum mechanics to gravity, you can show that it’s possible that space and time themselves can come into existence when nothing existed before. So that’s not a problem."<Note num={++notes}>
				Taken out of context, Dr. Krauss's argument makes about as much sense as Bill Wurtz's description of the beginning of the universe in his video describing the <Hyperlink to="https://youtu.be/xuCn8ux2gbs?t=12s">"history of the entire world, i guess":</Hyperlink>
				<blockquote>"[A] long time ago, actually never, also now, nothing is nowhere. when? never. MAKES SENSE, RIGHT? like i said, it didn't happen. nothing was never anywhere (that's why it's been everywhere). It's been so everywhere, you don't need a 'where.' you don't even need a 'when.' that's how <em>every</em> it gets... forget this. i wanna be something, go somewhere, do something, i want things to change. i want to invent time and space, and i know it's possible, because everything is here and it probably already happened. i just don't know when to start. and that's exactly where it started. oh, i paused it. i think there's a universe now."</blockquote></Note></blockquote>
				While scientific evidence should trump "common sense" whenever they conflict unless the latter is logically necessary, there is no need to throw logic out of the window here.<Note num={++notes}>...as Dr. Krauss very nearly suggested in the aforementioned debate.</Note> Krauss's argument commits the fallacy of equivocation by changing the definition of "nothing." Virtual particles emerge out of the quantum vacuum, which is an existing material thing with physical properties. They come into being from the pre-existing energy in that vacuum. Strictly speaking, they are something.
				<br /><br />
				Proponents of the KCA who <Hyperlink to="https://www.reasonablefaith.org/media/debates/the-craig-krauss-debate-at-north-carolina-state-university#presentation-5">say "nothing" really mean <em>nonbeing</em></Hyperlink>, the absence of any existing thing whatsoever. It does not even refer to literally empty space, because space exists. Its referent is null. While discussing cosmological arguments, The Thinker (writing for the blog Atheism And The City) <Hyperlink to="http://www.atheismandthecity.com/2012/09/refuting-william-lane-craig-kalam.html?m=1">complained that the "philosophical and metaphysical 'nothing' that theologians like Dr. Craig describe does not exist in reality,"</Hyperlink> which is exactly the point and is true by definition. It is also the only reason that the term "nothing" is useful. Contrary to The Thinker's characterization of Craig's definition of nothing as "philosophical and metaphysical," when people in general say "nothing" they often mean "absence of anything." Wikipedia defines nothing as "<Hyperlink to="https://en.wikipedia.org/wiki/Nothing">a concept denoting the absence of something[,] … the state of being nothing, the state of nonexistence of anything, or the property of having nothing."</Hyperlink> It also mentions that "In philosophy, to avoid linguistic traps over the meaning of 'nothing', a phrase such as not-being is often employed to make clear what is being discussed." Craig made this distinction when pushed and Krauss never did, but it would have cleared up quite a bit of confusion if both of them had done so from the start.
				<br /><br />
				A quick Google search defines "nothing" as "<Hyperlink to="https://www.google.com/search?q=nothing">not anything; no single thing</Hyperlink>" – in other words, absence. Google used "I said nothing" as an example sentence, which means "I did not say anything" rather than "I said empty space" or "I said the quantum vacuum." As another example, if an atheist says that nothing has supernatural powers, they do not mean that empty space has supernatural powers; they mean that there does not exist any thing with supernatural powers. Stephen Colbert pointed this out to Dr. Krauss while interviewing him about his book <em>A Universe from Nothing</em> on <em>The Colbert Report</em>: "<Hyperlink to="http://www.cc.com/video-clips/e6ik9l/the-colbert-report-lawrence-krauss">If there is no thing called God – if he is nothing – can't something come from him?</Hyperlink>" The question is facetious for the same reason that Krauss's argument is facetious: it equivocates on the definition of "nothing."
				<br /><br />
				In fairness to Krauss, he is not the only prominent physicist to describe the quantum vacuum as "nothing" to give it metaphysical importance. Alexander Vilenkin describes his model of the beginning of the universe as quantum tunneling from nothing into something, but as Dr. Craig pointed out, "the quantum tunneling is at every point a function from something to something."<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 115.</Note> Alan Guth also used the term "nothing" to describe the quantum void, as did Stephen Hawking.<Note num={++notes}>Embarrassingly, <Hyperlink to="https://www.theodysseyonline.com/everything-is-nothing">I actually used this exact same conflation</Hyperlink> in an article about astrophysics with the confusing and misleading title "Everything is Nothing."</Note>
      		</Section>
			<Section num={++sections} summary="The claim that God's timeless existence exempts him from the KCA's causal premise raises no clear objection to the KCA.">
				Confusion over definitions is at the heart of another objection to the KCA, namely, that if nothing comes from nothing then God could not have created the universe from nothing. Consider <Hyperlink to="https://youtu.be/5o62zvebQGE">TheMessianicManic's description of the objection</Hyperlink>:
				<blockquote>"A surprising number of apologists will argue that there must be a god, because it's impossible to make something from nothing [and that] therefore god must have made something from nothing … How does the idea that god made everything out of nothing make any more sense than the idea that everything made itself out of nothing? If it makes no sense for something to come from nothing, then it makes no sense for god to make something out of nothing."</blockquote>
				A defender of the KCA could respond that nothing comes from nothing <em>without a cause</em>. This may seem like an ad hoc adjustment of Lucretius's metaphysical principle, but it was technically already contained in the meaning of the principle. As Dr. Craig described, the KCA's use of the phrase <Hyperlink to="https://www.reasonablefaith.org/media/reasonable-faith-podcast/debate-on-the-kalam-argument">"comes from" refers to Aristotelian efficient causality</Hyperlink>, such that "<em>x</em> comes from <em>y</em>" means that "<em>y</em> is the efficient cause of <em>x</em>." An efficient cause refers to whatever brings something into being, and a material cause refers to the stuff of which something is composed. Dr. Craig's Christian view suggests that God was the logically prior efficient cause of the universe, and because he created it from nothing, the universe lacked a logically prior material cause. A KCA proponent can affirm without contradiction that whatever begins to exist has a prior efficient cause, and therefore God created the universe with no prior material cause.
				<br /><br />
				When the KCA proponent suggests that nothing comes from nothing, they could clarify that they really mean, "there is no thing which comes into being and lacks an efficient cause." One may notice that this has the same meaning as the first premise of the KCA. The equivalence explains how one can infer "everything that begins to exist has a cause" from "nothing comes from nothing" even though, without understanding that "come from" implies efficient causality, one may think that the causal aspect of the premise is ad hoc or arbitrary. To avoid confusion, KCA proponents would help themselves to phrase the metaphysical principle and the first KCA premise as "Everything that begins to exist has an efficient cause."
				<br /><br />
				Admittedly, I intended to use this KCA objection myself until reading Dr. Craig's response and realizing that the objection equivocates the meaning of "comes from."
        </Section>
      <Section num={++sections} summary="If the universe was supernaturally caused, only one cause should be assumed to exist because of Ockham's Razor.">
					The counter-apologetics website <Hyperlink to="http://www.argumentsforatheism.com/arguments_god_cosmological.html">Luke Mastin's ArgumentsForAtheism tried to rebut the KCA,</Hyperlink> which he called the "temporal cosmological argument," by claiming that it does not rule out the possibility that multiple gods could exist outside the universe. He questioned why the KCA proves the existence of only one God. Hilariously, he answered his own question in the previous sentence: "The widely accepted concept of 'Occam’s Razor' suggests that the simplest solution to a problem is always the best, and that additional unnecessary complexity should be avoided." Although his description of Ockham's Razor is inaccurately oversimplified, it is sufficient to refute their KCA objection. As Dr. Craig rightly pointed out, <Hyperlink to="https://www.reasonablefaith.org/podcasts/defenders-podcast-series-1/s1-cosmological-argument/the-cosmological-argument-part-1">positing multiple gods adds unnecessary complexity,</Hyperlink> so if gods are required to explain a phenomenon, one would be preferred.
        </Section>
			<Section num={++sections} summary="The claim that God's timeless existence exempts him from the KCA's causal premise raises no clear objection to the KCA.">
				<Hyperlink to="http://www.argumentsforatheism.com/arguments_god_cosmological.html">Luke Mastin</Hyperlink> and <Hyperlink to="http://patheos.com/blogs/secularoutpost/2015/03/13/gt-rebuttal-part-2-chapter-3">Jeffrey Jay Lowder argued</Hyperlink> that the first premise of the KCA is false because "everything that had a beginning <em>in time</em> has a cause," which is "why our observation shows that things which begin in the universe (and so in time) have a cause," but that "It’s logically impossible for time itself to have a cause since causes always precede their effects in time." This argument can be expressed in a syllogism as simple as the KCA itself:
				<br /><ol>
					<li>Every cause exists before its effects.</li>
					<li>Nothing existed before the beginning of time.</li>
					<li>Therefore, the beginning of time had no cause. (from 1 ∧ 2)</li>
				</ol><br />
				Dr. Craig responded to a similar objection by <Hyperlink to="https://www.reasonablefaith.org/writings/scholarly-writings/the-existence-of-god/creation-and-big-bang-cosmology/">asserting that God caused the universe simultaneously with its beginning</Hyperlink>. On this view, God existed at the time <em>t</em> = 0 and simultaneously caused the time <em>t</em> = 0 to exist. Lowder attempted to rebut this possibility by claiming that simultaneity still <Hyperlink to="http://www.patheos.com/blogs/secularoutpost/2015/03/13/gt-rebuttal-part-2-chapter-3/">"expresses a temporal relationship between causes and effects,"</Hyperlink> implying a contradiction because an atemporal entity cannot be simultaneous with a temporal effect. This technically misconstrues Craig's argument, because he <Hyperlink to="https://www.reasonablefaith.org/writings/scholarly-writings/divine-eternity/timelessness-and-omnitemporality/">claims that God is temporal</Hyperlink>. Perhaps that is a distinction without a difference, though, and Lowder really meant that it is impossible for a <em>timeless</em> being to be in a temporal relationship. In response, Craig has argued that God is timeless but entered time at the moment of creation, to which Chris Hallquist objected by claiming that Craig's use of the word "timeless" excludes the possibility that God is a thinking mind. For example, <Hyperlink to="https://www.reasonablefaith.org/media/debates/is-god-a-delusion/">Craig has denied that the first cause could be a computer,</Hyperlink> calling it is a "contradiction in terms" because a computer "has to function" and "takes time." Each of those descriptors accurately describes a mind as well. Minds must function and must take time to think. Hallquist further claims that it is <Hyperlink to="https://infidels.org/library/modern/chris_hallquist/faith.html#ch3">impossible to imagine a timeless mind which enters time</Hyperlink>. According to Hallquist, a timeless mind that created time is inconceivable because thinking takes time so a timeless mind is inconceivable, and because "from timelessness, only timelessness comes," a timeless God could not have made the temporal decision to create a universe. When Dr. Craig heard this objection from Edwin Curley in their debate, he replied by saying that <Hyperlink to="https://www.reasonablefaith.org/media/debates/the-existence-of-the-christian-god-the-craig-curley-debate/">"what's essential to personhood is self-consciousness and freedom of the will, and those are not inherently temporal concepts."</Hyperlink> As usual, Craig was ready with an authority to quote, in this case <em>The Timelessness of God</em> by John Yates:
				<blockquote>"The theist may immediately grant that concepts such as memory and anticipation could not apply to a timeless being. But this is not to admit that the key concepts of consciousness and knowledge are inapplicable to such a deity. There does not seem to be any essential temporal elements in words like 'to understand,' 'to be aware,' 'to know.' An atemporal deity could possess maximal understanding, awareness, and knowledge in a single, all-embracing vision of reality."</blockquote>
				These objections to the KCA exhibit what Daniel Dennett calls "the philosopher's fundamental foible: mistaking a failure of the imagination for an insight into necessity."<Note num={++notes}>Daniel Dennett, <em>Darwin's Dangerous Idea</em> p. 175, "Priming Darwin's Pump."</Note>
      </Section>
			<Section num={++sections} summary="The universe could not have caused itself to exist because a thing cannot be causally prior to itself.">
				Daniel Dennett replied to the KCA by arguing that the universe caused itself to exist, which Dr. Craig blasted as "plainly nonsense" and "logically incoherent" because <Hyperlink to="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-new-atheism-and-five-arguments-for-god/">"in order to create itself, the universe would have to already exist … before it existed!"</Hyperlink> To refute Dennett, Craig needed to assume that any cause must exist before its effect(s). If a cause could exist simultaneously with its effect, Craig's objection would be unsound – but Craig needed to affirm the actuality of simultaneous causation to refute a previous objection. Does this apparent contradiction allow Dennett to get away with what he called the "ultimate boot-strapping trick" and affirm that the universe caused itself? Alas, Craig invoked another distinction which allows him to wriggle out of this dilemma by claiming that "<Hyperlink to="https://www.reasonablefaith.org/writings/scholarly-writings/the-existence-of-god/creation-and-big-bang-cosmology/">the cause of the origin of the universe is causally prior to the Big Bang, though not temporally prior to the Big Bang."</Hyperlink> Given that no entity can be causally prior to itself, it is fair to say that God existed causally but not temporally prior to the universe even though the universe itself could not do the same.
				<br /><br />
				One may feel tempted to dismiss all of Dr. Craig's definitional maneuvers as distinctions without a difference. However, at the moment I am not aware of any principle which could legitimate that dismissal. The logical positivists' verification criterion of meaningfulness would work, since none of Craig's distinctions could be verified by human experience, but that criterion's many problems have already been discussed. To be conservative, in this case I have granted Dr. Craig any distinction that I cannot explicitly refute. Since not everyone would do the same, though, Craig's responses do seem somewhat precarious.
			</Section>
			<Section num={++sections} summary="The relativity of simultaneity shows that simultaneous causality is possible, so it is possible that God created the universe simultaneous with its beginning and did not have to exist before the universe to cause the universe to exist.">
				As previously mentioned, Jeffrey Jay Lowder made the following argument against the KCA by <Hyperlink to="http://patheos.com/blogs/secularoutpost/2015/03/13/gt-rebuttal-part-2-chapter-3">denying the possibility of simultaneous causality:</Hyperlink>
				<br /><ol>
					<li>Every cause exists before its effects.</li>
					<li>Nothing existed before the beginning of time (or "before the universe").</li>
					<li>Therefore, the beginning of time (or "the universe") had no cause. (from 1 ∧ 2)</li>
				</ol><br />
				Premises 1 and 2 are presupposed as true by definition, but the first is dubious. It is ostensibly considered to be self-evident in physics because it defines causality as follows: <Hyperlink to="https://en.wikipedia.org/wiki/Causality_(physics)">all effects must be caused by events in their past light cone, and no cause can have an effect outside of its future light cone.</Hyperlink> Even outside of physics, all time-lagged studies assume that A could not have caused B unless A happened before B. The principle appears to be even older than modern science, though. St. Thomas Aquinas, the original proponent of the cosmological argument, explicitly stated that all causes must precede their effects. He considered this fact to be necessary for the cosmological argument, as it was his basis for rejecting a self-caused entity: "[W]e never observe, nor ever could, something causing itself, for this would mean it preceded itself, and this is not possible."<Note num={++notes}>Aquinas, <em>Selected Philosophical Writings</em>, p. 200.</Note> Aquinas used "cause" and "precede" interchangeably, such that "X preceded Y" necessarily follows from "X caused Y."
				<br /><br />
				However, there are problems with these arguments that causes must temporally precede their effects. First and foremost is the <em>relativity of simultaneity</em>: two events which are simultaneous from one frame of reference can occur one after the other from another frame of reference. This empirical implication follows directly from the theory of relativity, and entails that if two events can be causally linked and occur simultaneously from some frame of reference. Modern physics does not deny simultaneous causality. Lowder attempted to rebut the possibility of God's simultaneous causation of the universe by claiming that labeling God the 'cause' and the universe the 'effect' becomes meaningless if they are simultaneous. But the relativity of simultaneity shows that it is possible for one thing to causally precede another without temporally preceding it, so the labeling is not arbitrary.
				<br /><br />
				Second, time-lagged studies only work based on a denial of retrocausality on an everyday scale (too large for quantum physics to be relevant, and too similar in reference frame for relativity to be relevant), not necessarily based on a denial of simultaneous causality. Even if they assumed that causes always temporally precede effects, that does not vindicate the assumption. Finally, when Aquinas used the term "precede," he most likely meant <em>causally</em> rather than <em>temporally</em> precede.
      </Section>
			<Section num={++sections} summary="Neither God's existence nor his knowledge entail that actual infinities exist because God and his knowledge are qualitatively, not quantitatively, infinite.">
				One supposed problem with the KCA that I thought of lies in Zeno's paradox of Achilles and the tortoise, arguing that Zeno's paradox shows that actual infinities can exist in reality, namely in the distance that Achilles travels. However, one potential resolution to the paradox comes not from accepting actual infinities but from the fact that quantum physics includes a minimum possible unit of distance and time: the Planck length and time, respectively. Values of distance of time below the Planck units are physically impossible.
				<br /><br />
				Edwin Curley attempted a much stronger argument in his debate against Dr. Craig, <Hyperlink to="https://www.reasonablefaith.org/media/debates/the-existence-of-the-christian-god-the-craig-curley-debate/">claiming that the KCA disproves God</Hyperlink> when it asserts that "actual infinities" do not exist because God is actual and infinite. Craig responded by pointing out that "when theologians talk about the infinity of God, this isn't a mathematical concept ... the infinity of God isn't a mathematical concept at all" because an "actual infinity" is "a collection of an infinite number of definite and discrete finite parts." Atheists including Jeff Allen and Adam Lee responded by <Hyperlink to="http://infidels.org/library/modern/jeff_allen/kalam.html">claiming that God's omniscience necessitates actual infinities</Hyperlink> because God knows a truth, knows that he knows a truth, ad infinitum such that <Hyperlink to="http://www.patheos.com/blogs/daylightatheism/essays/unmoved-mover/#cosmological:modern">God's knowledge contains an actually infinite</Hyperlink> number of definite and discrete propositions. However, Craig responded to this idea by saying that <Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/is-god-actually-infinite">God's knowledge of the universe is intuitive, not propositional:</Hyperlink> God knows about the universe in the same way that humans can know things based on intuitions or sensations without formulating them as propositions. The recursive knowledge to which Allen and Lee referred may only exist potentially and not actually because God would need to recall it before it exists. God's knowledge could be stored intuitively and then recalled propositionally if needed. God's omniscience would not necessitate that God consciously thinks all of his knowledge at once, since omniscience only entails that he can potentially recall any knowledge — which is not difficult to imagine, because humans do not recall all of their knowledge at once.
			</Section>
			<Section num={++sections} summary="Positing as the KCA does that everything either did or did not begin to exist requires no justification, since it is true analytically that either X or not-X.">
				<Hyperlink to="https://infidels.org/library/modern/dan_barker/kalamity.html">Dan Barker claimed that the KCA is circular</Hyperlink> because its first premise "implies that reality can be divided into two sets: items that begin to exist (BE), and those that do not (NBE)" and that "NBE (if such a set is meaningful) cannot be empty, but more important, it must accommodate more than one item to avoid being simply a synonym for God." While he admits that an empty set can be meaningful, he claims that an empty set can only be meaningful if "we can point to non-zero examples of this set in real life," since a set is only meaningful "if we know what constitutes an item [in] that set." No one has observed a beginningless item, so he infers that the set of beginningless items is cognitively meaningless. Notice that, according to Barker, some term must refer to an object of experience in order to be meaningful. Barker presupposes the (self-refuting, as previously described) verification criterion of meaningfulness in this answer, because if a noun can be meaningful without referring to some object of experience, then one could refer to a meaningful empty set of that term's referents.
				<br /><br />
				When Barker asks, "By what observations or arguments is the possibility of beginningless objects warranted?" he ignores the basic principles of modal logic, because it is logically possible for something to exist even if it that thing has not been observed. A sufficient answer to his question is that the possibility of a beginningless object is established by the fact that it is conceivable and entails no contradiction. Think about an object, and then imagine a possible world where it never began to exist. For example, imagine a rock that sits in an empty void forever, uncaused and unchanging. The rock is a beginningless object. The rock does not exist, and if no beginningless objects have been observed, then it is meaningful to say that the set of real beginningless objects is empty. To say otherwise invokes the self-refuting verification criterion of meaningfulness, so a more satisfying answer to Barker's question is "It is the twenty-first century — take your logical positivism and go back to the early twentieth!"
				<br /><br />
				Barker admitted that beginningless objects are conceivable, but nevertheless asks for a "justification of NBE" based on experience. As Dr. Craig pointed out, "<Hyperlink to="https://www.reasonablefaith.org/question-answer/P540/barkers-objection-to-the-kalam-argument">this is just a confusion of meaning and reference</Hyperlink>" because two terms can have different meanings even if they refer to the same object. While it would have been more charitable for Craig to recognize that Barker's objection makes sense under the verification criterion of meaningfulness, and the <Hyperlink to="https://plato.stanford.edu/entries/names/#2.1">Millian theory of proper names</Hyperlink> to which it is closely related, Craig is nevertheless correct. As previously described, Gottlob Frege demonstrated that meaning and reference to an existing thing are different by describing a situation where "Homer believed that the Morning Star was the Morning Star" is true while "Homer believed that the Morning Star was the Evening Star" is false. Also, Barthes demonstrated that meaning and reference to an existing thing are different by pointing out that positivists would find names of fictional entities meaningless.
				<br /><br />
				Barker argued that if the only beginningless object supposed is God, then the first KCA premise "is equivalent to 'everything except God has a cause,'" which "puts God into the definition of the premise of the argument that is supposed to prove God's existence, and we are back to begging the question." However, as Craig pointed out, dividing reality into the two sets BE and NBE simply applies the law of the excluded middle: some thing is either X or it is not X. Since it would be possible to refer to the empty set NBE, the KCA does not beg the question simply by referencing NBE.
			</Section>
    <Link to="/">Go back to the homepage</Link>
  </Layout>
)

export default CosCraig