import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import Hyperlink from "../components/Hyperlink"
import Image from "../components/image"
import Note from "../components/Note"
import SEO from "../components/seo"
import Section from "../components/Section"

var notes = 0;
var sections = 0;
const DemographicsUSA = () => (
  <Layout>
    <SEO title="Demographics USA" />
      Discussions of demographic trends regarding religious belief and adherence often start out by mentioning two particular TIME Magazine covers from the 1960s, so I may as well do the same. In April 1966, the cover of TIME Magazine asked, "Is God Dead?" But in December 1969, the cover apparently reversed its position by asking, "Is God Coming Back to Life?" Usually, the flip-flop is used to frame a specific narrative — for example, that theism is on the rise, especially in scholarly circles,<Note num={++notes}>Dr. Craig, <Hyperlink to="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-resurrection-of-theism/">"The Resurrection of Theism."</Hyperlink></Note> or that religious demographic trends vary and fluctuate.<Note num={++notes}>Tom W. Smith (2012), <Hyperlink to="http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.371.3239">Beliefs about God across Time and Countries"</Hyperlink> (<Hyperlink to="http://www.norc.org/pdfs/beliefs_about_god_report.pdf">PDF</Hyperlink>). Chicago: NORC/University of Chicago.</Note> The latter is closer to the truth, but a third option fits the data even more accurately: American religion is declining.
      <ol>
        <Section num={++sections} summary="Fewer and fewer Americans have identified as Christian every year since the mid-20th century, as consistently shown by many credible polling organizations and contradicted by none, while more and more Americans identify as nonreligious." class="hidden full content">
          The percentage of American identifying as Christian has declined for over sixty years, as found consistently by every polling organization that has checked. The most notable and credible are probably the Pew Research Center, the General Social Survey, and Gallup.
          <br /><br />
          In 2007 and 2014, the Pew Research Center conducted intensive surveys to study <Hyperlink to="https://www.pewforum.org/2015/05/12/americas-changing-religious-landscape/">"America's Changing Religious Landscape."</Hyperlink> They surveyed <Hyperlink to="https://www.pewforum.org/religious-landscape-study/">more than 35,000 Americans from all 50 states about their religious affiliations, beliefs and practices, and social and political views</Hyperlink> During the same time, they also conducted regular yearly surveys of American political and religious affiliation. Both survey methods found the same result: <Hyperlink to="https://www.pewforum.org/2019/10/17/in-u-s-decline-of-christianity-continues-at-rapid-pace/pf_10-17-19_rdd_update-00-020/">American Christianity is declining fast.</Hyperlink> Americans are increasingly leaving religion behind.
          <br /><br />
          <Hyperlink to="https://www.pewforum.org/2019/10/17/in-u-s-decline-of-christianity-continues-at-rapid-pace/pf_10-17-19_rdd_update-00-020/"><img width="494" height="1024" src="https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?w=494" class="attachment-large size-large" alt="In U.S., smaller share of adults identify as Christians, while religious 'nones' have grown" srcset="https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png 624w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=145,300 145w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=494,1024 494w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=154,320 154w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=195,405 195w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=200,415 200w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=260,539 260w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=310,643 310w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-020.png?resize=420,871 420w" sizes="(max-width: 494px) 100vw, 494px" /></Hyperlink>
          <br /><br />
          Christian identification is shrinking, and nonreligion is rising, not only as a percentage of the American population but in raw numbers:
          <br /><br />
          <img src = "./pew-religious-landscape.png" />
          <br /><br />
          Contrast a Pew report from 2001<Note num={++notes}>I chose 2001 because this was the earliest Pew publication I could find about American religious identification demographics.</Note> which found that 82% of Americans identified as Christian — down slightly from a whopping 84% in 1996. Only about 10% of Americans were nonreligious back then. These data suggest a trend: the American population has steadily become less Christian.
          <br /><br />
          Young, college-educated Democrats are not the only ones becoming less Christian. No, <Hyperlink to="https://www.pewforum.org/2019/10/17/in-u-s-decline-of-christianity-continues-at-rapid-pace/pf_10-17-19_rdd_update-00-017/">Christianity's decline spans every demographic group in the United States:
          <br /><br />
          <img width="751" height="1024" src="https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?w=751" class="attachment-large size-large" alt="Broad-based declines in share of Americans who say they are Christian" srcset="https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png 838w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=220,300 220w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=768,1047 768w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=751,1024 751w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=160,218 160w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=297,405 297w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=200,273 200w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=260,354 260w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=310,422 310w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=420,572 420w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=640,872 640w, https://www.pewforum.org/wp-content/uploads/sites/7/2019/10/PF_10.17.19_rdd_update-00-017.png?resize=740,1008 740w" sizes="(max-width: 751px) 100vw, 751px" /></Hyperlink>
          <br /><br />
          The decline of American Christianity is not a new trend. In 1972, the National Opinion Research Center (NORC) began conducting yearly interviews with nationally representative samples of thousands of Americans: the <Hyperlink to="https://gss.norc.org/">"General Social Survey"</Hyperlink> (GSS). Their interview questions include religious identification. Like Pew's surveys, the GSS found that <Hyperlink to="https://gssdataexplorer.norc.org/variables/287/vshow">Christian identification has fallen while nonreligious identification rose.</Hyperlink>
          <br /><br />
          <Hyperlink to="http://sociology.berkeley.edu/sites/default/files/faculty/fischer/Hout%20et%20al_No%20Relig%20Pref%202012_Release%20Mar%202013.pdf"><img src = "./gss-religion.png" /></Hyperlink>
          <br />
          Gallup probably has the most data on the <Hyperlink to="https://news.gallup.com/poll/1690/religion.aspx">long-term decline of American Christianity</Hyperlink>:
          <br /><br />
          <Hyperlink to="https://news.gallup.com/poll/117409/easter-smaller-percentage-americans-christian.aspx" ><img src = "https://content.gallup.com/origin/gallupinc/GallupSpaces/Production/Cms/POLL/r23235jxbuuc7z7_ywneqq.gif" /></Hyperlink>
          <br /><br />
          <Hyperlink to="https://news.gallup.com/poll/128276/Increasing-Number-No-Religious-Identity.aspx"><img src = "https://content.gallup.com/origin/gallupinc/GallupSpaces/Production/Cms/POLL/zkhxmzvbekozvpl6obartg.gif" /></Hyperlink>
          <br /><br />
        </Section>
        
        <li class = "summary" id = "AmericanDemographyContent2Summary" onclick = "toggleShownSubArg(this.id);">American religious belief and behavior have declined alongside religious belief. Americans are not simply becoming less fond of Christian organizations; Americans are increasingly abandoning religion entirely.</li>
        <div id = "AmericanDemographyContent2" class = "hidden full content">			
          American Vice President Mike Pence <a href = "http://twitter.com/VP/status/995379097881759744" target="_blank" rel="noopener">claimed</a> that "Religion in America isn’t receding – just the opposite," because <a href = "http://twitter.com/VP/status/995378911897845761" target="_blank" rel="noopener">supposedly</a> the "percentage of Americans who live out their religion on a weekly basis – by praying, going to church, and reading and believing in the Bible – has remained remarkably consistent over the decades." Yet Pence's beliefs about American religious demographics are almost as inaccurate as his religious beliefs. While Gallup lacks long-term year-over-year data on prayer and scripture-reading frequency, what they do have shows the <a href = "https://news.gallup.com/poll/1690/religion.aspx" target="_blank" rel="noopener">decline of American religious behavior</a> over the last few decades. According to Gallup, the proportion of Americans who...
          <br /><ul>
            <li>..."attend church or synagogue ... never" almost doubled from 14% in 1992 to 27% in 2017, while the proportion who attended "every week" declined from 34% in 1992 to 23% in 2017.</li>
            <li>..."attend[ed] church or synagogue in the last seven days" declined from 40% in 1992 to 35% in 2017.</li>
            <li>...believe that "the Bible is the actual word of God and is to be taken literally, word for word" declined from 38% in 1976 to 24% in 2017.</li>
            <li>...believe that "the Bible is an ancient book of fables, legends, history, and moral precepts recorded by man" doubled from 13% in 1976 to 26% in 2017.</li>
          </ul><br />
          <a href = "https://news.gallup.com/poll/200186/five-key-findings-religion.aspx"><img src = "https://content.gallup.com/origin/gallupinc/GallupSpaces/Production/Cms/POLL/9--8-h7dueiagrhcjnjvfq.png" />
          <img src = "https://content.gallup.com/origin/gallupinc/GallupSpaces/Production/Cms/POLL/wrzapq-n9uoi6r4b5sxydw.png" /></a>
          <br /><br />
          Some have alleged that the decline in religious behavior and identification does not mean a decline in religious belief. While discussing his book <em>Bad Religion</em> on <em>Real Time with Bill Maher</em>, Ross Douthat of the <em>New York Times</em> contested the claim that American religious belief is declining by presenting what he considered a nuanced view of the demographic shifts in religion. He acknowledged that "<a href = "https://youtu.be/kJQjpG-lGY4">organized religion [is] weaker than ever before</a>," but also claimed that "Americans are still as religious as ever" because "more people claim a direct experience of the divine than they did in the 1950s, people are still as likely to say they believe in God, and so on. If you drop below 'Do you go to church on Sunday?' and ask 'What do people actually believe?' [then] religion's as potent as ever."
          <br /><br />
          Douthat's first example is surprisingly correct, because the <a href = "http://www.pewresearch.org/?p=1434/multiple-religious-practices-reincarnation-astrology-psychic" target="_blank" rel="noopener">proportion of Americans reporting a religious/mystical experience has doubled since 1962</a>, but his second example is demonstrably false. Gallup found that <a href = "https://news.gallup.com/poll/193271/americans-believe-god.aspx" target="_blank" rel="noopener">American belief in God has declined since the late 1960s</a>. It has not declined as quickly or consistently as Christian identification, or as quickly as nonreligious identification has risen, but it has declined nonetheless. Pew's Religious Landscape Study also found a slight <a href = "https://www.pewresearch.org/fact-tank/2015/11/04/americans-faith-in-god-may-be-eroding/">decline of American belief in God</a> from 92% in 2007 to 89% in 2014. The decline of "[b]eliev[ing] in God with absolute certainty" over the same period was even faster, from 71% to 63%.
          <br /><br />
          <a href = "https://news.gallup.com/poll/193271/americans-believe-god.aspx"><img src = "./belief-in-god-polls.png" /></a>
          <br />
          In 1967, 1% of Americans told Gallup that they do not believe in God. In 2017, <a href = "https://news.gallup.com/poll/1690/religion.aspx" target="_blank" rel="noopener">12% of Americans told Gallup they do not believe in God, the highest known percentage in American history</a>.
          <br /><br />
          In the United States, religion is increasingly seen as "<a href = "https://news.gallup.com/poll/128276/Increasing-Number-No-Religious-Identity.aspx" target="_blank" rel="noopener">largely old-fashioned and out of date</a>," as Gallup has shown:
          <br /><br />
          <a href = "https://news.gallup.com/poll/128276/Increasing-Number-No-Religious-Identity.aspx" target="_blank" rel="noopener"><img src = "https://content.gallup.com/origin/gallupinc/GallupSpaces/Production/Cms/POLL/fo0icpvbpke6wlft2xzeug.gif" /></a>
        </div>
        <li class = "summary" id = "AmericanDemographyContent3Summary" onclick = "toggleShownSubArg(this.id);">The decline of religion in the United States is caused by higher intelligence, better education, and better access to information. The decline accelerated in the past few decades because the Internet has vastly increased most Americans' access to information.</li>
        <div id = "AmericanDemographyContent3" class = "hidden full content">
          My explanation for the decline of American religion will probably seem infuriatingly cliche or boring: Americans are becoming less religious because they are learning more and becoming smarter. It would be easy to dismiss as atheist rhetoric, if not for the significant amount of evidence showing that it is true. I review some of this evidence from demographic surveys below.
          <br /><br />
          Daniel Dennett claimed that the <a href = "https://www.brainyquote.com/quotes/quotes/d/danieldenn513760.html">Internet could cause the downfall of religion</a>: "Now that mobile phones and the Internet have altered the epistemic selective landscape in a revolutionary way, every religious organisation must scramble to evolve defences or become extinct." Again, while it would be too easy to dismiss his claim as mere rhetoric, it actually matches the available evidence. Allen Downey analyzed the General Social Survey data on the decline of religion and found that the rise of <a href = "https://www.technologyreview.com/s/526111/how-the-internet-is-taking-away-americas-religion/">Internet use explains 25% of the decline in American religious affiliation</a>. It is possible that some third factor explains the rise of Internet use and the rise of American irreligion, "[b]ut Downey discounts this possibility" because his study "controlled for most of the obvious candidates, including income, education, socioeconomic status, and rural/urban environments." So as more Americans gained easy access to more information and more different perspectives than their own, they increasingly abandoned their religious beliefs. 
          <a href = "https://www.technologyreview.com/s/526111/how-the-internet-is-taking-away-americas-religion/"><img src = "https://cdn.technologyreview.com/i/images/Religion.png?sw=2500" /></a>
          A survey of nonreligious American college students by a Christian outreach group called the Fixed Point Foundation also discovered the <a href = "https://www.theatlantic.com/national/archive/2013/06/listening-to-young-atheists-lessons-for-a-stronger-christianity/276584/" target="_blank" rel="noopener">link between Internet use and religious nonbelief</a>:
          <blockquote>
          "When our participants were asked to cite key influences in their conversion to atheism--people, books, seminars, etc. -- we expected to hear frequent references to the names of the "New Atheists." We did not. Not once. Instead, we heard vague references to videos they had watched on YouTube or website forums."
          </blockquote>
          Downey also found that 25% of the decline is explained by a decline in the percentage of Americans who have a religious upbringing. The less that Americans are taught to follow their religion as children, before the development of their critical thinking skills, the fewer of them ever come to believe it.
          <br /><br />
          Yet to say that American Christianity is dying "because of higher Internet use" or "because fewer have a religious upbringing" is not to offer a full explanation, even though I offered a few plausible reasons above. Fortunately, several groups have investigated the causes of American Christianity's decline. As a follow-up to their Religious Landscape Study, Pew Research Center surveyed the 78% of nonreligious Americans who were raised religious but left their religion behind. The respondents were asked a simple, open-ended question: Why did you leave your religion?
          <br /><br />
          The results should discourage any American Christians. Few of these American apostates are merely non-practicing (8%) or too busy for religion (2%). By a landslide, the <a href = "https://www.pewresearch.org/fact-tank/2016/08/24/why-americas-nones-left-religion-behind">most common reason for Americans to leave their religion is no longer believing it</a>:
          <blockquote>
          “About half of current religious 'nones' who were raised in a religion (49%) indicate that a lack of belief led them to move away from religion. This includes many respondents who mention 'science' as the reason they do not believe in religious teachings, including one who said 'I’m a scientist now, and I don’t believe in miracles.' Others reference 'common sense,' 'logic,' or a 'lack of evidence' – or simply say they do not believe in God.” 
          </blockquote>
          <a href = "https://www.pewresearch.org/fact-tank/2016/08/24/why-americas-nones-left-religion-behind"><img src = "./pew-nones-survey.png" /></a>
          <br />
          The second most popular reason was not even half as common: 20% of American apostates reported leaving because they dislike institutional religion. Pew also "asked religious 'nones'" for "<a href = "https://www.pewresearch.org/fact-tank/2018/08/08/why-americas-nones-dont-identify-with-a-religion/">the single most important reason they are unaffiliated</a>":
          <blockquote>
          “Again, questioning religious teachings is among the top responses, with a quarter of all 'nones' saying it is the most important reason. A similar share (22%) cite lack of belief in God, and 16% say the most important reason is that they dislike the positions churches take on social and political issues.”
          </blockquote>
          <a href = "https://www.pewresearch.org/fact-tank/2018/08/08/why-americas-nones-dont-identify-with-a-religion/"><img src = "https://www.pewresearch.org/wp-content/uploads/2018/08/FT_18.08.07_whyUnaffiliated_questioning.png" /></a>
          <br />
          Disliking religious leaders and organizations together made up 8% of responses. So Gallup researcher Frank Newport was <a href = "https://news.gallup.com/opinion/polling-matters/260738/why-americans-losing-confidence-organized-religion.aspx">wrong when he claimed</a> that "the drop in confidence in 'the church or organized religion' does not necessarily equate to a drop in confidence in religion" because "people may simply be shifting their underlying religious and spiritual instincts to new and different outlets, with organized religion increasingly left behind." Disliking organized religion was nowhere near as common of a main reason for American apostasy as abandoning religious belief.
          <br /><br />
          Perhaps increased Internet access helps explain why more people are rejecting religion based on ideas of science and rationality, since more people can access more information. Downey noted another factor which helps link rational thinking with the decline of American religion: 5% of the decline is explained by the increasing percentage of Americans with a college education. More education predicts less religious belief,<span class = "note"><span class = "notetext">Albrecht and Heaton found a <a href = "https://www.jstor.org/stable/3511041?seq=1#page_scan_tab_contents">negative correlation between religiosity and educational attainment among Americans</a> in their 1984 article: "Secularization, Higher Education, and Religiosity." They notably also found that within denominations, higher church attendance predicted better education. Since this may be a <a href = "https://en.wikipedia.org/wiki/Simpson%27s_paradox">Simpson paradox</a>, each trend merits its own explanation. In general, people who learn more become less religious; but within religious communities, perhaps those with the highest levels of dedication or conscientiousness attend church more frequently. Or perhaps the explanation is economic, as <a href = "https://doi.org/10.1023/B:REHO.0000031614.84035.8e">Lehrer showed in 2004</a> about conservative Protestant American women. Still, the salient point is that overall, education predicts lower religious belief.</span></span> so as more Americans are exposed to new ideas and learn how to think abstractly in an academic setting, fewer of them accept religion.
          <a href = "https://www.census.gov/library/visualizations/time-series/demo/cps-historical-time-series.html"><img src = "https://www.census.gov/content/dam/Census/library/visualizations/time-series/demo/fig2.jpg" /></a>
          Accounting for those three factors, though, still leaves 45% of the decline unexplained. Downey already accounted for the usual demographic factors, so what could explain the missing 45%? Although I have not run my own analysis, I suspect that a nonzero percentage is explained by another factor. This factor (1) has been repeatedly found to predict less religious belief,<span class = "note"><span class = "notetext">The meta-analysis of research on the <a href = "https://doi.org/10.1177%2F1088868313497266">negative relationship between intelligence and religiosity</a> by Zuckerman, Silberman, and Hall in 2013 is so excellently summarized in its abstract that I will simply copy (most of) it here:
          <blockquote>
          "A meta-analysis of 63 studies showed a significant negative association between intelligence and religiosity. The association was stronger for college students and the general population than for participants younger than college age; it was also stronger for religious beliefs than religious behavior...Three possible interpretations were discussed. First, intelligent people are less likely to conform and, thus, are more likely to resist religious dogma. Second, intelligent people tend to adopt an analytic (as opposed to intuitive) thinking style, which has been shown to undermine religious beliefs. Third, several functions of religiosity, including compensatory control, self-regulation, self-enhancement, and secure attachment, are also conferred by intelligence. Intelligent people may therefore have less need for religious beliefs and practices."
          </blockquote></span></span> (2) is closely related to education as well as rational thinking, and (3) has been consistently risen in the United States over the past century: intelligence.
          <br /><br />
          The rise of intelligence is known as "the Flynn effect," named after the scientist who discovered it, James Flynn. He discovered that the <a href = "https://doi.org/10.1177%2F1745691615577701">average IQ score has been steadily rising</a>, <a href = "https://en.wikipedia.org/wiki/Flynn_effect#Rise_in_IQ">"in every age range, at every ability level, and in every modern industrialized country."</a> The <a href = "https://doi.org/10.1037%2Fa0037173">average American IQ has risen</a> by 3 IQ points per decade for <a href = "https://ourworldindata.org/intelligence">over a century:
          <br /><br />
          <img src = "https://ourworldindata.org/uploads/2013/07/ourworldindata_pietschnig-and-voracek-flynn-effect.jpg" /></a>
          To clarify, I know that there are plenty of intelligent religious people, and that becoming smarter does not necessarily make someone nonreligious. I cannot claim with much confidence that rising intelligence has reduced American religion, because I have not found any studies linking the rise of American intelligence to the decline of American religion. Yet since intelligence has risen so much recently and is negatively correlated with religious belief, it likely explains part of the decline.
          <br /><br />
          To summarize all of the evidence above, the rise of education, intelligence, and access to information are slowly choking American Christianity to death. 
        </div>
      </ol>
    



  </Layout>
)

export default DemographicsUSA
