import React from "react"
import { Link } from "gatsby"
import Hyperlink from "../components/Hyperlink"
import Section from "../components/Section"
import Note from "../components/Note"

import Layout from "../components/layout"
import SEO from "../components/seo"

var notes = 0;
var sections = 0;
const MoralArg = () => (
  <Layout>
    <SEO title="William Lane Craig's Moral Argument" />
    In his debate with Lawrence Krauss, William Lane Craig phrased <Hyperlink to="https://www.reasonablefaith.org/media/debates/the-craig-krauss-debate-at-north-carolina-state-university#presentation-2">his moral argument for God's existence</Hyperlink> as follows:
    <br /><br /><blockquote>
        "On a naturalistic view moral values are just the byproduct of biological evolution and social conditioning … on the atheistic view there doesn’t seem to be anything about this that makes this morality objectively binding and true. But the problem is that objective moral values and duties plausibly do exist … There’s no more reason to deny the objective reality of moral values than the objective reality of the physical world … But in that case, the probability of God’s existence is 1.0! We can formulate this reasoning as follows: 1. If God did not exist, objective moral values and duties would not exist. 2. Objective moral values and duties do exist. From which it follows logically and inescapably that 3. Therefore, God exists."
    </blockquote>
    Yet the objectivity of morality has nothing to do with the existence of the Christian god and everything to do with realism regarding metaphysical universals. If universals exist, as Platonic Forms or universal essences, then an object can instantiate the essence or form of goodness to some degree. If universals do not exist, then no object can instantiate the essence or form of goodness to any degree.
    <Section num={++sections} summary="Moral realism depends on metaphysical realism, not theism. So, an atheist who is a metaphysical realist can endorse moral realism, while a Christian metaphysical anti-realist could not.">
		Goodness is a matter of category membership: some things would belong to the category of "good things," and some would not. This applies even to things that are "better" or "worse," given that it is possible for a thing to be more or less suited to a particular category. Metaphysical essentialism entails that category membership is objective; i.e. the category membership of an object is inherent to the object itself. Conversely, metaphysical anti-realism entails that category membership is subjective; i.e. categories are defined by observers, so the category membership of an object is only assigned by some observer(s), so it is not inherent to the object itself. Therefore, metaphysical realism entails moral realism and metaphysical anti-realism entails moral anti-realism, regardless of one's religious beliefs or lack thereof.
		<br /><br />
		A metaphysical essentialist can believe that an object instantiates goodness to a certain degree and is objectively good to that degree, but a metaphysical anti-realist must assign objects to the category of "good" or not based on subjective criteria. To a metaphysical anti-realist, describing the goodness of an object says nothing about the object and only describes a fact about some subject's belief about the object. 
		<br /><br />
		One can then precisely define the counterexamples to Dr. Craig's assertion that a Christian can believe in objective morality but an atheist cannot. An atheist who is a metaphysical realist can believe in objective morality, but a Christian who is a metaphysical anti-realist cannot.
		<br /><br />
		Consider an atheistic platonist who believes that there exists a Form of the Good, but does not believe in any non-physical thing that can think, feel, or act. Such an atheist can easily believe that morality is objective. An action, individual, or situation is morally good to the extent that it instantiates the Form of the Good, whatever that means. Atheistic objective morality is easier to understand in the case of an atheistic Aristotelian-essentialist, who believes that each thing instantiates its universal essence but does not believe that there exists a thinking, feeling, acting creator deity. Aristotle's essentialism entails his teleology by claiming that each thing has a telos as an essential property, and his teleology entails his virtue theory by pointing out that each thing must strive towards its <em>telos</em>. For an atheistic platonist or Aristotelian-essentialist, morality is objective because the goodness of a thing is in the object itself, not in anyone's opinion about the object.
    </Section>
    <Section num={++sections} summary="Craig's objections to what he calls 'atheistic moral platonism' dispute only its moral semantics and its moral epistemology, not its moral ontology. By his own reasoning, they are irrelevant.">
		Dr. Craig has objected to atheistic moral platonism because he does not know what it would mean to say that justice exists in the absence of people, because "Moral values seem to exist as properties of persons, not as mere abstractions," and even if they existed then it is hard to understand how one could come to know them.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 178.</Note> He also does not understand how moral duties are binding given atheistic moral platonism, and considers it an unlikely coincidence that humans' evolved moral sense matches the abstract forms of goodness.<Note num={++notes}>Craig, <em>Reasonable Faith</em> p. 179.</Note>
		<br /><br />
		I generally have no desire to defend platonism of any kind, but Craig's objections are quite strange and explicitly hypocritical in their irrelevance. Starting from the last objection and working backwards, an atheistic moral platonist could argue that evolution is teleological and works towards the good, based on an innate tendency of all things to do so. Even if evolution is unlikely to lead to the correct moral sense, though, the possibility that most humans are wrong or deluded about morality has nothing to do with the existence of objective moral values and duties. Dr. Craig's moral argument at no point requires that those values and duties be easily comprehensible or intuitive – to invalidate it requires only the mere logical possibility that they could exist in the absence of God.
		<br /><br />
		Ironically, Dr. Craig has conflated moral epistemology with moral ontology by claiming that atheistic moral platonism is impossible (if it was even possible, then the second premise of his moral argument would be incorrect) because it is unknowable. I call this <Hyperlink to="https://www.reasonablefaith.org/question-answer/P90/keeping-moral-epistemology-and-moral-ontology-distinct">ironic because of the explicit emphasis Craig has placed on the distinction</Hyperlink> between moral semantics, epistemology, and ontology to support his moral argument:
		<br /><br /><blockquote>
            "The claim that moral values and duties are rooted in God is a Meta-Ethical claim about Moral Ontology, not about Moral Linguistics or Epistemology. It is fundamentally a claim about the objective status of moral properties, not a claim about the meaning of moral sentences or about the justification or knowledge of moral principles.
            <br /><br />
            I’m convinced that keeping the distinction between moral epistemology and moral ontology clear is the most important task in formulating and defending a moral argument for God’s existence of the type I defend. A proponent of that argument will agree quite readily (and even insist) that we do not need to know or even believe that God exists in order to discern objective moral values or to recognize our moral duties. Affirming the ontological foundations of objective moral values and duties in God similarly says nothing about how we come to know those values and duties. The theist can be genuinely open to whatever epistemological theories his secular counterpart proposes for how we come to know objective values and duties."
        </blockquote>
		When defending his moral argument for God's existence, Dr. Craig evidently failed to complete what he considers the "most important task in formulating and defending a moral argument for God’s existence" by claiming (1) that our evolved moral sense is unlikely to match the Form of the Good, and (2) that this disqualifies atheistic moral platonism as a counterexample to his moral argument. 
		<br /><br />
		Dr. Craig claimed that atheistic moral platonism cannot explain why moral duties are binding, assuming that moral duties are binding if grounded in divine commands. He also claimed that atheistic moral platonism would make objective morals unknowable, and he claimed not to know what it would mean to say that justice exists in the absence of people. All three of these objections are based on his inability to understand the concept of instantiation. Given atheistic moral platonism, it is possible for justice to exist as a property of persons despite no persons existing – it would simply be an uninstantiated property. Properties are not contingent on instantiation in platonism, unlike Aristotelian-essentialism. As previously mentioned, if something objectively exists but is unknowable then it still objectively exists, so even if Craig is right that objective morals would be unknowable under atheistic moral platonism, it is irrelevant. Still, an atheistic moral platonist could probably argue that objective morality is known in the same way that other objective properties, like redness or size, are known: perception of the forms within whatever particulars instantiate them. Again, if evolution progresses teleologically towards the form of the good, then one would be hard-pressed to specify a basis to posit a disconnect between morals as they are perceived and the true form of morals. Craig's question of knowability would turn into an epistemic debate over the merits of perception. Finally, actions are good if and only if they instantiate goodness given atheistic moral platonism. By the definition of a duty, one ought to perform actions which instantiate goodness. It is not clear what Craig finds so difficult to understand there. Perhaps he means that no actions can be described as obligatory without being expressed as commands by another person. Even if that is correct, an atheistic moral platonist need not care, because they could still objectively call some actions "good" or "bad" and rank them in order of goodness. 
		<br /><br />
		Dr. Craig's claim that objective moral duties are not binding unless expressed as divine commands seems to express the converse of the truth: if morals do not exist as universals, then there are no objective moral values or duties whether or not God exists. An anti-realist must deny that morality is objective because no object can contain or instantiate goodness – including Christian nominalists and conceptualists. Even if they adhere to divine command theory, they must adcknowledge that morality is nothing more than God's opinion.
		<br /><br />
		Given Christian nominalism or conceptualism, morality is subjective because the moral value of any thing is not in the thing itself, the <em>object</em>, but in God's opinion of that thing, such that he is the <em>subject</em>. Since God's opinion of an object is subjective – i.e. in an individual's mind rather than in the thing itself – morality based on God's opinion is necessarily subjective. Suppose a Christian nominalist or conceptualist metaphysical belief system such that God exists but forms and essences do not. One could quite reasonably respond to any of God's "divine commands" by saying, in the immortal words of The Dude from <em>The Big Lebowski</em>, <Hyperlink to="http://knowyourmeme.com/memes/thats-just-like-your-opinion-man">"Yeah, well, y'know, that’s just, like, your opinion, man."</Hyperlink> God's opinion has no <em>a priori</em> priority over anyone else's given metaphysical anti-realism. Incidentally, this is where the Euthyphro dilemma comes from.
    </Section>
    <Section num={++sections} summary="The Euthyphro Dilemma can only be solved by bringing up God's essence, which shows that moral realism depends on metaphysical realism and not on theism.">
		The Euthyphro dilemma puts Christians between two undesirable conclusions. The first option is that an action is good because God commands it, so goodness is arbitrarily selected by God. This option makes it hard to argue that morality is “objectively true,” since morality comes from someone’s opinion – God’s opinion. The second option is that God commands an action because the action is good. This option means that there must be an objective standard of goodness independent of God, effectively making God irrelevant to any person’s morality.
		<br /><br />
		As Dr. Craig recognized, the only way to escape the dilemma is to argue that <Hyperlink to="https://www.reasonablefaith.org/writings/question-answer/euthyphro-dilemma">goodness is essential to God’s nature, so God’s traits are necessarily good</Hyperlink>. In this view, God's actions are morally good because God's nature is perfectly good, and his actions flow from his nature. God’s commands are still our standard for goodness, but goodness no longer seems arbitrary. The Euthyphro question, though, can be asked again: Are those traits are good because they are God’s, or are they God’s because they are good? Craig chooses the former, but says that this is no paradox because God is defined as the maximally perfect being.
		<br /><br />
		Notice that Dr. Craig implicitly recognizes that the objectivity of morality is based on essentialism instead of theism. He is able to successfully argue that God is objectively good only by presupposing that God has a universal essence, and not by appealing to some kind of distinction between theism and atheism. By admitting that actions are not good solely because God commands them, Craig also recognizes the possibility that Christianity is true and morality is subjective. If God exists but does not have the essential property of being good, as a Christian anti-essentialist must believe, then God exists but goodness is still subjective.
    </Section>
  </Layout>);
export default MoralArg;