
import React from "react"

// Components
import Layout from "../components/layout"
import Hyperlink from "../components/Hyperlink"
import Note from "../components/Note"
import SEO from "../components/seo"
import Section from "../components/Section"

var notes = 0;
var sections = 0;
const AnselmOnt = () => (
  <Layout>
    <SEO title="Anselm's Ontological Argument" />
    <script>
        {notes = 0}
        {sections = 0}
    </script>    
    <p>Anselm's ontological argument (AOA) for God's existence was first described in Anselm's <em><Hyperlink to="http://jasper-hopkins.info/proslogion.pdf">Proslogion</Hyperlink></em>:
    <br /><br /><blockquote>
        [I]s there, then, no such nature [as God], for the Fool has said in his heart that God does not exist? But surely when this very same Fool hears my words "something than which nothing greater can be thought," he understands what he hears ... So even the Fool is convinced that something than which nothing greater can be thought is at least in his understanding; for when he hears of this [being], he understands [what he hears], and whatever is understood is in the understanding. But surely that than which a greater cannot be thought cannot be only in the understanding. For if it were only in the understanding, it could be thought to exist also in reality—something which is greater [than existing only in the understanding]. Therefore, if that than which a greater cannot be thought were only in the understanding, then that than which a greater cannot be thought would be that than which a greater can be thought! But surely this [conclusion] is impossible. Hence, without doubt, something than which a greater cannot be thought exists both in the understanding and in reality.
    </blockquote><br />
    Yet for several reasons, Anselm's ontological argument (AOA) is insufficient to show that God exists.</p>
    <Section num={++sections} summary="Anselm's ontological argument conflates God with the concept of God, only proving that the latter exists.">
        The first problem of note is equivocation on what "God," or rather "that than which a greater cannot be thought," means. If "God" refers to <em>the concept of</em> an omniscient, omnipotent, omnibenevolent, omnipresent entity, then I will readily affirm that God exists – but only in the mind. A concept "existing in the mind" refers to a thought, as opposed to an <em>example</em> of that concept existing in the world. Concepts are abstractions from examples perceived in the actual world, and are stored in the mind. A demonstration that someone can imagine Anselm's maximally great being only shows the existence of a thought.
        <Note num={++notes}>
            Even if concepts could exist outside the mind, though, the equivocation problem holds given that "nothing can be its own form" (Thomas Aquinas, <Hyperlink to="http://www.newadvent.org/summa/1005.htm"><em>Summa Theologiae</em> 1:5</Hyperlink>).
        </Note> so no <em>X</em> is identical to the Form or essence of <em>X</em>.
        <br /><br />
        Some Christian apologists have <Hyperlink to="http://www.strangenotions.com/god-exists/">unironically listed Anselm's ontological argument alongside Aquinas's Five Ways</Hyperlink> in their attempts to prove that God exists.<Note num={++notes}>See also William Lane Craig, <em>Reasonable Faith</em> ch. 3, pp. 95-99.</Note> Yet if they had read Aquinas's original formulation of his Five Ways,<Note  num={++notes}>See Thomas Aquinas, <em>Summa Theologiae</em> 1:2</Note> they would have also found <Hyperlink to="http://www.newadvent.org/summa/1002.htm">Aquinas's swift refutation of Anselm's ontological argument</Hyperlink>:
        <blockquote>"Someone hearing the word <em>God</em> may very well not understand it to mean <em>that than which nothing greater can be thought</em>; indeed, some people have believed God to be a body. And even if the word <em>God</em> were generally recognized to have that meaning, nothing thus defined would thereby be granted existence in the world of fact, but merely in thought. Unless one is given that something in fact exists than which nothing greater can be thought – and this nobody denying God's existence would grant – the conclusion that God in fact exists does not follow."<Note  num={++notes}>Thomas Aquinas, <em>Selected Philosophical Writings</em>, "Passage 20: There Exists A God," p. 197.</Note></blockquote>
        The ontological argument can define the concept of God into existence in one's mind, but it cannot define God into existence in the actual world. It is a testament to Aquinas's brilliance as a philosopher that he summarized the ontological argument in a paragraph<Note  num={++notes}>Thomas Aquinas, <em>Selected Philosophical Writings</em>, "Passage 20: There Exists A God," p. 196.</Note> and refuted it in a paragraph. Aquinas wrote Passage 20 of his <em>Summa Theologiae</em> from 1266 to 1268,<Note  num={++notes}>Thomas Aquinas, <em>Selected Philosophical Writings</em>, "Passage 20: There Exists A God," p. 195.</Note> meaning that any theist using the classical formulation of the ontological argument is trying to resurrect an argument refuted almost 800 years ago by one of the most influential Christian philosophers in history.
    </Section>
    <Section num={++sections} summary="Existence is not a property, so it cannot be part of a thing's definition. If adding 'existing' to something's definition implies that it exists, then one can prove that anything exists.">
        <Hyperlink to="https://www.reddit.com/r/DebateReligion/comments/5v4z11/parodies_of_the_modal_ontological_argument_do_not/">'Existence' is not a property, so it cannot be part of the definition</Hyperlink> of a concept, including the concept of God:
        <Note num={++notes}>
            This was the second and most famous part of Immanuel Kant's objection to the ontological argument.
        </Note>
        <br /><br />
        <blockquote>"To say that something exists or does not exist is just to say that its properties are or are not exemplified in the world. When one says that an apple is red, sweet and round, for instance, one is describing its properties. But if they add that the apple "exists" they are not describing a further property possessed by the apple but merely telling you that the apple and its properties are exemplified. Anslem, Kant concluded, was inferring the existence of God out of an illicit conception of existence and nonexistence as properties that can be imputed to God."</blockquote>
        To assert that a thing <em>x</em> has a property <em>P</em> just is to assert that if <em>x</em> exists, then the property <em>P</em> is exemplified (that is, exists) in <em>x</em>. So to assert that God has the property of "existence" is to assert that if God exists, existence exists in God. Even ignoring that the latter part of that phrase seems so ill-posed as to be incoherent, the whole phrase says nothing about whether God actually exists.
        <br /><br />
        Consider a "realicorn," defined as a unicorn that actually exists. It is impossible to think of a realicorn that does not exist, so according to the reasoning of the ontological argument, if one recognizes the idea of the realicorn then one must recognize that realicorns exist! "<Hyperlink to="https://youtu.be/kT9Z8ER_640?t=2m40s">Simply adding existence to the definition of a thing does not conjure it into existence."</Hyperlink> If imagining a realicorn does not prove its existence, imagining God cannot prove God's existence.
    </Section>
    <Section num={++sections} summary="Even if a maximally great being exists, it need not be a single entity since it could be many beings of equal greatness. It also need not be divine. Possibly, each human is maximally great.">
        William of "<Hyperlink to="https://www.iep.utm.edu/ockham/#SH6bi">Ockham’s curt response to the ontological argument</Hyperlink>" was that the top level of a hierarchy of greatness need not be God. In fact, it need not even be one entity, given that multiple individuals can be equally great: "If God and the angels do not exist, then human beings are the greatest entities, and there is no single best among us. Notice that, even if there were a single best among humans, he or she would be a 'god' in a very different sense than is required by Catholic orthodoxy." Even granting all of the premises of Anselm's ontological argument, one could legitimately respond that each human is the greatest entity imaginable, providing no reason to believe in God. After all, "God" is defined by Anselm as merely "that than which nothing is more noble and more perfect," so if the most perfect things are humans than every human qualifies as God.
        <Note  num={++notes}>
            Ockham, <em>Philosophical Writings</em> pp. 125-126.
        </Note>
    </Section>
    Some of the objections to Anselm's ontological argument, however, are unsound:
    <Section num={++sections} summary="Imagining a maximally evil being does not reduce AOA to absurdity as some objectors have claimed because, if goodness is identical to existence as Anselm and other medievals assumed, then a maximally evil being is maximally nonexistent.">
        Adam Lee of "Daylight Atheism" tried to use a <em>reductio</em> to refute the ontological argument like Guanilo did, calling it the "Manichaen Reductio": "<Hyperlink to="http://www.patheos.com/blogs/daylightatheism/essays/unmoved-mover/#manichaean">[S]uppose we try to conceive of the most evil being imaginable. By the logic of the ontological argument, must this being not exist as well?</Hyperlink>" Evidently Lee failed to understand that Anselm's ontological argument presupposes, as did many medieval Christian theologians, the Augustinian idea that goodness is identical to existence.<Note num={++notes}>St. Augustine, <em>De Doctrina Christiana</em>, i, 42, as cited in St. Thomas Aquinas, <Hyperlink to="http://www.newadvent.org/summa/1005.htm"><em>Summa Theologiae</em> 1:5</Hyperlink></Note> Given that goodness is identical to existence, the maximally evil being is maximally nonexistent, so a proponent of Anselm's ontological argument need not worry about Lee's objection. It presupposes that greatness is objective but fails to use the proponents' definition of greatness. As described, there are plenty of other objections for such a proponent to worry about.
    </Section>
    <Section num={++sections} summary="If greatness is objective, then one must believe in objective greatness to believe in God via Anselm's ontological argument. And it seems that one must believe in God to believe in objective greatness according to the moral argument, making Anselm's argument circular. However, AOA and the moral argument both argue from the existence of greatness to God's existence.">
        I used to object to Anselm’s ontological argument about the property of “greatness.” As a property, greatness exists either objectively or subjectively. If subjective, the degree of an object's greatness depends on the perspective from which its greatness is observed, showing that its greatness exists only in the mind of the observer. If objective, the degree of an object's greatness is invariant, showing that its greatness exists in the object itself.
        <br /><br />
        If greatness is subjective, then God has completely different properties depending on one's perspective. Then if God exists, he has different properties to different people, showing that his properties — and therefore God himself, since a thing is all of its properties — exist only in the mind of the observer. Likewise, if greatness is subjective, one could deny that it is greater to exist than not to exist. In Buddhism, the greatest state of affairs is to attain nonexistence. A maximally great being would be nonexistent, so a Buddhist could use the ontological argument to disprove God. The first part of Immanuel Kant's refutation of Anselm's ontological argument was "<Hyperlink to="https://youtu.be/kT9Z8ER_640?t=1m">questioning why existing is greater than not existing."</Hyperlink> Asserting that existence is greater than nonexistence seems to cross the fact-value distinction, after all.
        <br /><br />
        I had thought that if greatness is objective, and has value, then one must presuppose the existence of objective value to call anything "great" – and that <Hyperlink to="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/can-we-be-good-without-god/">according to Christians like Dr. Craig, one can only know that objective value exists if one presupposes that God exists</Hyperlink>. Hence, God's existence must be assumed to argue that something is "maximally great" or "greater" than anything else. The ontological argument would then be circular: One must know that God exists to know that greatness exists, according to the moral argument, but one must know that greatness exists to know that God exists using the ontological argument. Asserting that something is "maximally great" presupposes the existence of greatness, which (according to Craig) presupposes the existence of God.
        <br /><br />
        However, comparing the ontological argument and the moral argument in terms of their deductive structure dismisses this problem of circularity. They have the same basic structure: If greatness/goodness exists, then God exists; greatness/goodness exists; therefore God exists. I had thought that "greatness only-if God; greatness; therefore God" and "God if greatness; greatness; therefore God" were different structures, but they are logically identical. So a proponent of Anselm’s ontological argument can say that greatness exists objectively without the problem of circularity which I alleged.
    </Section>
</Layout>);

export default AnselmOnt;