import React from "react"
import { Link } from "gatsby"

// Components
import Layout from "../components/layout"
import Hyperlink from "../components/Hyperlink"
import Image from "../components/image"
import Note from "../components/Note"
import SEO from "../components/seo"
import Section from "../components/Section"

var notes = 0;
var sections = 0;
const PossibleWorlds = () => (
  <Layout>
    <SEO title="Possible Worlds Semantics" />
    Consider the possibility that <em>y</em> happens to <em>x</em>. Does that thing, the "possibility," exist?
    <br /><br />
    Any possibility either exists outside of human minds or it does not. If it does, then possibilities about what could happen to any <em>x</em> either exist within <em>x</em> or they do not. So possibility exists either inside minds and not actual things, outside of minds but inside actual things, or outside of minds and outside actual things. The first view is modal conceptualism. The second is an Aristotelian-Thomist view that every actual thing contains "potencies" which it can actualize. The third is possible world semantics.
    <Section num={++sections} summary="Possible worlds semantics claims that every possibility exists in its own entire universe, which implies that every possible universe exists. That is 'modal realism,' the least parsimonious idea that anyone has ever created.">
        Possible worlds semantics claims that for every possibility, that possibility exists outside our universe, in its own universe where it is true. Consider a possible world exactly like the actual world, except that in it the temperature yesterday was 1° hotter in New York City. Claiming that this "possible world" exists is claiming that another universe exists alongside our own — like the many-worlds interpretation of quantum mechanics, but instead of claiming that every <em>physically</em> possible world exists, it claims that every <em>logically</em> possible world exists. There would be infinitely many more logically possible worlds than physically possible ones, by the way. That is why the belief that all possible worlds are equally real, "modal realism," is the most metaphysically egregious belief that anyone can coherently hold. Nothing violates Ockham's (ontological) razor more than modal realism.
        <br /><br />
        Yet modal realism is inescapable for anyone who claims that there is a non-actual possible world outside the mind. The only differences between the actual world and the 1° hotter world are temperature and existence. So if one claims that both of them "exist," for example by saying "<em>there is</em> a possible world where yesterday was 1° hotter," then the only difference between the two worlds is temperature. So possible worlds semantics entails modal realism.
        <br /><br />
        At this point the proponent of possible worlds semantics may protest that possible worlds do exist, but less than the actual world: they only exist <em>possibly</em> and not <em>actually</em>. But one cannot claim that a possible world exists but not actually, because actuality is existence. I know no coherent interpretation of the phrase "non-actual existence." One may protest that possible existence is a different kind of existence, intermediate between nonexistence and actuality. But the idea of intermediate existence is inconceivable, and cannot be explained in terms of anything conceivable.
    </Section>
    <Section num = {++sections} summary="All true statements about possibility and necessity can be explained in terms of logical, physical, or epistemic possibility or necessity.">
        Compare modal realism to the Aristotelian-Thomistic view and to conceptualism in interpreting the sentence, "It is possible that this lamp will fall over." The A-T view posits that there exists a potential for falling in the lamp. Modal realism posits that there exists an entire universe containing a lamp that will fall over. Conceptualism posits that the idea of the lamp falling over (1) entails no contradiction, (2) violates no law of physics, and/or (3) is not known to be false. Notice that modal realism adds infinite universes which exist in some inexplicable way to one's ontology, the A-T view adds many "potencies" (whatever those are) to one's ontology, and no form of conceptualism adds anything to one's ontology.
        <br /><br />
        As a modal conceptualist, I affirm that all true modal statements are about (1) whether an idea contradicts itself, (2) whether an idea contradicts the laws of physics, or (3) whether something is known. For example, "this lamp could fall over" is true by all three standards. "Hillary Clinton could have been President" is true by the first and second. "There might be a god" is true by the first and third. Logical, physical, and epistemic possibility should suffice to explain all true modal statements — and there had better be a good reason to claim otherwise, since claiming otherwise adds the maximum amount of a strange new kind of entity to one's ontology. 
    </Section>
    <Section num={++sections} summary="Possible worlds semantics either claims that every possibility exists in its own universe, or fails its only task of defining what 'possibility' and 'necessity' means.">
        The defender of possible worlds semantics may protest that saying "there is a possible world <em>w</em>" only means that <em>w</em> possibly exists and does not actually exist, so therefore positing possible worlds is not metaphysically egregious. But this admits the utter failure of possible worlds semantics. Possible worlds <em>semantics</em> is intended to explain what possibility <em>means</em>: "possibly" supposedly means "in some possible world," and "necessarily" supposedly means "in every possible world." Claiming that "there is a possible world <em>w</em>" only means "<em>w</em> possibly exists" argues in a vicious circle. It defines possibility in terms of possible worlds, and possible worlds in terms of possibility.
        <br /><br />
        Possible worlds semantics is only useful in so far as it can explain what possibility <em>means</em>; that is why it is called a kind of "semantics." Any proponent of possible worlds semantics who refuses to define what distinguishes a possible world from the actual world has admitted that possible worlds semantics is useless, because it has failed to explain what "possibility" means. Defining "possibly X" as "there is a possible world where X" can only explain possibility through its other terms: "there is a" and "world." Either possible worlds semantics fails to define possibility and is therefore useless, or it defines possibility by declaring the existence of an entire world containing X. The latter entails modal realism. Believing in (1) a useless semantics of possible worlds, or (2) modal realism, is egregious either way.
        <br /><br />
        Note that in any sections later in this document where I use possible worlds semantics, I do so only for the sake of argument. Any subsequent part discussing "possible worlds" should implicitly be prefaced by "If there are possible worlds, then..." There are no extra-mental possible worlds, and "possibility" only exists conceptually.
        <br /><br />
        The Stanford Encyclopedia of Philosophy (SEP) notes that there are <Hyperlink to="https://plato.stanford.edu/entries/possible-worlds/#ConceptionsOfPWs">three mainstream analyses of possible worlds: "concretist," "abstractionist," and "combinatorialist."</Hyperlink> It uses "concretism" as another way to say modal realism. But as I described, one can reject modal realism because it is the most unparsimonious idea that anyone has ever come up with. To the "abstractionist," all possible worlds are "states of affairs (SOAs)," that is, "abstract, intensional entities typically signified by sentential gerundives like 'Algol's being John's pet' and 'There being more than ten solar planets'." Yet this fails to escape my earlier critique, because "SOAs constitute a primitive ontological category for the abstractionist." Recall that a "primitive ontological category" is a category that one cannot explain in terms of some other category. Since the goal of metaphysics is to have as few primitive categories as possible, there should ideally only be one primitive ontological category: existence. Choosing SOAs as a different ontological primitive would not bother me if it was the abstractionist's only ontological primitive. However, the abstractionist has another ontological primitive:
        <br /><br /><blockquote>
        "to say an SOA is non-actual is not to say that it does not actually exist. It is simply to say that it is not, in fact, a condition, or state, that the concrete world is actually in. However, because ‘____ is actual’ is often used simply to mean ‘____ exists’, there is considerable potential for confusion here. So, henceforth, to express that an SOA is actual we will usually say that it obtains."
        </blockquote>
        In other words, the abstractionist must claim that "being actual" is different from "existing." But the abstractionist has made a distinction without a difference. She has two options: to explain this distinction in terms of some difference between actuality and existence, or not. I can think of no (real or conceptual) difference between actuality and existence, and I have never encountered an abstractionist attempting to provide one. So perhaps the abstractionist is claiming that the difference is inexplicable and primitive -- but that means that the abstractionist is unparsimoniously introducing multiple ontological primitives that one could just as easily do without by rejecting all talk of possible worlds. 
        <br /><br />
        Note that abstractionism falls right into the earlier accusation of circularity. Given abstractionism, "abstract possible worlds are defined in irreducibly modal terms — a possible world is an SOA that (among other things) possibly obtains; or a set of propositions such that it is possible that all of its members are true; or a property that is possibly exemplified; and so on." So by explicitly defining possible worlds in terms of possibility, and possibility in terms of possible worlds, the abstractionist has explicitly admitted the failure of possible worlds semantics. One response given by abstractionists is, yet again, a resort to "primitives." According to the SEP, "abstractionists can argue that we begin with a primitive notion of modality and ... subsequently discover an intimate connection to the notion of a possible world." It is the mark of a poor theory like abstractionism to call all of its ideas "unanalyzable primitives" upon discovering that, on analysis, its ideas are all redundant and superfluous. 
        <br /><br />
        As the SEP admits, "the fact that modality is a primitive in abstractionist definitions of possible worlds arguably compromises its ability to provide semantically illuminating truth conditions for the modal operators." It responds by claiming that abstractionism "illuminate[s] the connection" between possibility and possible worlds "that serves as such a powerful conceptual tool for constructing philosophical arguments" like Plantinga's free will defense or modal ontological argument. Yet those arguments presuppose abstractionism; to use them to defend abstractionism is again circular. Each is also plagued by several other problems which I discuss elsewhere in this document, making them poor examples to justify the framework of possible worlds semantics. 
        <br /><br />
        If the idea of possible worlds is an ontological primitive, as some abstractionists have argued, then why was <Hyperlink to="https://en.wikipedia.org/wiki/Possible_world#Possibility,_necessity,_and_contingency">Gottfried Leibniz the first to <strike>invent</strike> discover it in 1710?</Hyperlink> A primitive notion is one which cannot be explained and/or understood in terms of anything else. So a primitive concept cannot be learned through philosophical analysis, because to learn a primitive concept, one would have to understand it in terms of pre-existing knowledge.<Note num={++notes}>To quote the <Hyperlink to="https://www.iep.utm.edu/fodor/#H6">Internet Encyclopedia of Philosophy’s article on Jerry Fodor</Hyperlink>,
        <blockquote>
        "Standard models of concept learning thus do not apply to primitive concepts that lack internal structure. For instance, one cannot formulate the hypothesis that red things fall under [the idea of] RED unless one already has RED, for the concept RED is a constituent of that very hypothesis. Therefore, primitive concepts like RED cannot be learned, that is, they must be innate."
        </blockquote></Note> Since a primitive concept is one that anyone can understand and believe without explanation, it is extremely unlikely that the idea of possible worlds is primitive but was never thought of until 1710. It is not enough to argue that the concept of <em>possibility</em> has been known since ancient times, because one can coherently discuss possibility without ever invoking "possible worlds." To call the idea of "possible worlds" an ontological primitive is not only a lazy excuse to avoid justifying possible worlds semantics. The idea that possible worlds are primitive is not only egregious but absurd.
    </Section>
  </Layout>);

  export default PossibleWorlds  