import React from "react"
import { Link } from "gatsby"
import Hyperlink from "../components/Hyperlink"
import Section from "../components/Section"
import Note from "../components/Note"

import Layout from "../components/layout"
import SEO from "../components/seo"

var notes = 0;
var sections = 0;
const TrinityModern = () => (
  <Layout>
    <SEO title="Modern Scientific Analogies for the Trinity" />
    Four Christians to whom I brought my argument that Trinitarian doctrine is contradictory and therefore should not be believed all gave the same kind of reply: analogies with scientific theories. They claimed that the most successful physical theories contain apparent contradictions, but still should be believed. They gave three examples of apparent contradictions in physics: The simultaneous truth of quantum mechanics (QM) and the theory of relativity, <Hyperlink to="https://en.wikipedia.org/wiki/Resonance_(chemistry)">resonance structures</Hyperlink> as an example of quantum superposition, and wave-particle duality.
    <Note num={++notes}>
        Here are the specific objections that each of those Christians gave me, although I have kept them anonymous because I am quoting from private correspondence:
        <br /><ul>
        <li>"The other big question I had on the trinity section was why you think someone can't hold the resolvability of contradictions on authority, even if they don't see the resolution themselves. I think light is a wave and a particle and that waves are not particles, but I also don't think I'm rationally committed to believing every proposition by the principle of explosion."</li><br />
        <li>"Do you believe that photons exist? Or more generally that light exists? The point: Our current understanding of light is that it is both a wave and a particle, both non-local (wave) and local (particle). Light cannot be directly looked at, only its effects can be observed; we can't see the essence of light nor can we describe our theories about its essence without using contradictions like the one above. Yet, we both believe that light exists, and that we can know certain things about how it acts, even that we can express certain aspects of its nature, albeit through contradictory claims (again above).<br /><br />It's just a thought I had because you said something about how we can't believe in things if we don't know what they are. But we don't know what light is, except that it's the thing that makes all the effects that we associate with light. Same argument for God. We don't know what God is, not fully at least, but we know he's the thing that makes all the effects that are associated with him. In the same way one is able to make claims about the properties of light, one ought to be able to make claims about the character of God. Unless you don't believe light exists...in which case...?"</li><br />
        <li>"This sets too high a standard for any belief system. If resolution of every <em>apparent</em> contradiction (every paradox) was required to believe anything, then none of us could ascribe to any scientific theory. A study with 99.99999% accuracy would still need to be rejected because one data point contradicts the others.<br /><br />Furthermore, ask any reputable physicist today and he or she will profess belief both in General Relativity and Quantum Mechanics (the latter of which is the best demonstrated scientific theory in history), and yet both of these theories currently conflict with each other. There is a certain faith on the part of physicists that with more research a new unified theory will emerge, but there is no guarantee. Yet for the meantime, two points lead them to believe conflicting theories: (1) strong evidence points to both, [and] (2) there is no direct logical contradictions, only apparent ones. Both of these conditions are true of the doctrines of the Christian Faith."</li><br />
        <li>"I think I just found an example that can sufficiently explain the Trinity in nature: The quantum mechanical description of resonance structures between atoms in Chemistry ([n]ot between atoms, but resonance structures within an atom) ... From what I was able to understand, the idea of resonance structures of chemical compounds necessitates that two given structures be occupying the same space at any given time."</li>
    </ul>
    </Note> But none of these show contradictions within physics.
    <Section num={++sections} summary="The simultaneous truth of quantum mechanics (QM) and the theory of relativity entails no contradiction because the two have been reconciled by string theory.">
        The first example that those Christians brought up, the apparent contradiction between quantum mechanics and relativity, backfires. Consider how one physicist called the Bohmian interpretation of quantum mechanics "<Hyperlink to="https://youtu.be/RlXdsyctD50?t=10m43s">certainly wrong, and I don't think anyone could deny that, because it doesn't account for relativity (either special or general) and that means it's at best incomplete. While regular mechanics has quantum field theory as its relativistic version, [Bohmian] pilot wave theory hasn't quite got there yet.</Hyperlink>" That physicist said that an interpretation is "<em>certainly wrong</em>" — his words, not mine — because it contradicts relativity. Yet he pointed out that quantum field theory is a relativistic formulation of QM. 
        <br /><br />
        Quantum field theory coheres with special, but not (yet) general, relativity.
        <Note num={++notes}>
            "The Schrödinger equation treats space and time as separate in the old-fashioned, Newtonian way ... Nowadays, modern quantum field theories fully incorporate the melding of space and time predicted by special relativity. And yet, they still don’t fully incorporate the warping of space and time predicted by general relativity." Quote from PBS Space Time, "<Hyperlink to="https://youtu.be/YNEBhwimJWs?t=169">Quantum Gravity and the Hardest Problem in Physics.</Hyperlink>"
        </Note> So as a relativistic formulation of quantum mechanics, it is not quite enough to show the consistency of QM with relativity. However, the analogy comparing the contradiction between quantum mechanics and relativity to the Trinity contradiction forgets that science has a stricter epistemic standard than theology. There is at least one idea — string theory — which "<Hyperlink to="https://doi.org/10.1007/978-3-540-71117-9_12">passed all conceivable consistency checks</Hyperlink>"
        <Note num={++notes}>
            J. Louis, T. Mohaupt, and S. Theisen, "<Hyperlink to="https://doi.org/10.1007/978-3-540-71117-9_12">String Theory: An Overview</Hyperlink>," <Hyperlink to="https://pure.mpg.de/rest/items/item_150398/component/file_150397/content">PDF</Hyperlink> p. 1; see also <Hyperlink to="https://www.quora.com/Why-might-string-theory-be-the-only-mathematically-consistent-theory-of-quantum-gravity">Quora</Hyperlink>.
        </Note> while resolving quantum mechanics and relativity. It has not been universally accepted as true only because it lacks evidence and testable predictions. If an analogous theological idea included a coherent, non-heretical interpretation of the Trinity, I doubt that many theologians would wait for empirical testing before endorsing that idea.
        <br /><br />
        Quantum field theory has not fully incorporated general relativity because it has not incorporated how gravity warps spacetime. <Hyperlink to="https://youtu.be/YNEBhwimJWs">The problem of quantizing gravity</Hyperlink> is — very roughly — that most fields are quantized with respect to a continuous grid of spacetime, but GM shows that gravity just is spacetime curvature, so the spacetime grid cannot be quantized with respect to itself. If gravity is merely excitation in a quantized field, as quantum gravity would require, then that excitation interacting with itself would increase its own energy infinitely. A few measurements can correct this same problem in other quantum field theories, but for quantum gravity infinite measurements would be required. There are two ways to fix this problem coherently: to search for ways to quantize gravity while avoiding those infinities, as <Hyperlink to="https://en.wikipedia.org/wiki/Loop_quantum_gravity">loop quantum gravity</Hyperlink> does; or to say that spacetime is emergent from more fundamental quantum phenomena, as string theory does. 
        <br /><br />
        Some researchers have shown that in some possible universes, <Hyperlink to="https://www.quantamagazine.org/string-theory-only-game-in-town-tests-20150218/">string theory is the only consistent way to reconcile relativity and quantum mechanics</Hyperlink>. If it is "the only game in town" in our universe as well, then its truth follows deductively from the truth of relativity, quantum mechanics, and the principle of non-contradiction. The enormous troves of evidence for both physical theories would combine as evidence for string theory. 
        <br /><br />
        String theory shows that relativity and QM can be reconciled, so the only question is how to reconcile them rightly. So, one can believe in both and resolve the apparent contradiction. Apparent contradictions within physics theories should motivate people to research physics more to understand why there is not really a contradiction. Nothing has shown that the contradictions in Trinitarian doctrine can be reconciled.
    </Section>
    <Section num={++sections} summary="Neither resonance structures nor wave-particle duality shows any contradiction within physics, because various interpretations of quantum mechanics have explained those without contradiction.">
        <Hyperlink to="http://reed.edu/chemistry/roco/Resonance/wavefn.html">Resonance is some kind of (quantum) superposition</Hyperlink>, so what it "really is" — and what that implies for Trinitarian theology — depends on how one interprets quantum mechanics:
        <br /><br /><ul>
            <li>Given the many-worlds interpretation, superposition of X and Y only means that X is in one timeline and Y is in another. So if God is the superposition of three persons, then each is in a different timeline. But that is heresy.</li>
            <li>Given the traditional Copenhagen interpretation, superposition of X and Y only means that the thing is not really X or Y until measured. It has a probability of being X, and one of being Y, after the measurement. So if God is the superposition of three persons, then God is not any person until something like a "measurement," after which God is one person. But that is heresy.</li>
            <li>Etc.</li>
        </ul>
        One may object that I am taking the analogy too literally. But "literal" means that a statement direct matches a belief, and "metaphor" means it indirectly matches one. There still has to be a coherent belief, and it still has to be able to be said using language. So if someone thinks she "believes" a metaphor, but cannot describe it literally, the metaphor matches no belief in her mind. Instead, it only matches a vague feeling. But no vague feeling is a belief.
        <br /><br />
        One of the Christians also mentioned that one data point contradicting the others in a study means that the study should not be believed. But two different data points describing different spacetime locations cannot "contradict" one another; only propositions can contradict each other. A data point can directly contradict a theory, but only if the outcome excluding that data point is deductively entailed by the theory, which only happens when the theory predicts an outcome with 100% certainty. Yet most scientific theories rarely predict an outcome with that level of certainty.
        <br /><br />
        Finally, consider wave-particle duality. This will also depend on one's interpretation of quantum mechanics. For example, the <Hyperlink to="https://en.wikipedia.org/wiki/Wave%E2%80%93particle_duality#2._Wave-only_view">many-worlds interpretation would probably claim that light is always only a wave</Hyperlink>, and <Hyperlink to="https://en.wikipedia.org/wiki/Wave%E2%80%93particle_duality#1._Both-particle-and-wave_view">Bohmian mechanics would claim that light has wave-like and particle-like properties</Hyperlink>. As usual, there are plenty of interpretations that resolve the apparent contradictions — and the only reason the competing interpretations are still around is a lack of empirical predictions to test which one is correct. Since the apparent contradictions can be resolved, the only question is how to resolve them rightly. Also, the aforementioned Christians claimed that one can know <em>that</em> God is even if one cannot know <em>what</em> God is, and one of them supported this by making an analogy with light. But the analogy with light backfires. One can know <em>that</em> light is only because light is observable, unlike God.
    </Section>
</Layout>)

export default TrinityModern;